### ISSUE TITLE
Unboxable CollectionType

### ISSUE THREAD

**Issue by simme** [JohnSundell/Unbox#100]
Hello,

I've got an Unboxable model that I just implemented `CollectionType` conformance on and now I'm getting compile errors about `Ambiguous use of 'unbox(_:isKeyPath:)'. I realize _why_ this is happening. But I'm having a hard time figuring out how to make the compiler pick the unbox method that is for "single objects" rather than the collection type one.

So basically I have:
```swift
struct SomeModel: Unboxable {
  // ..
}

extension SomeModel: CollectionType {
  // ..
}
```

And try to use it in this context:
```swift
struct SomeOtherModel: Unboxable {
  let models: [SomeModel]
  public init(unboxer: Unboxer) {
    // This line yields the error.
    models = unboxer.unbox("models")
  }
```

I realize this is not a support forum. So I won't be offended if this issue is closed and forgotten without an answer :) But having a hard time finding the answer elsewhere.

**Comment by simme** [comment]
Worked around with this for now. Maybe it's the only possible solution?
```swift
        let modelsRaw: [UnboxableDictionary] = unboxer.unbox("models")
        models = try! Unboxer.performCustomUnboxingWithArray(modelsRaw, context: nil, allowInvalidElements: false) { (unboxer) -> SomeModel in
            do {
                let model: SomeModel = try Unbox(unboxer.dictionary)
                return model
            } catch {
                fatalError("Unable to unbox model")
            }
        }
```

**Comment by JohnSundell** [comment]
Hi @simme! To me, this is definitely partly a support forum - an easy way to ask questions and get answers from the community, so your questions are more than welcome! 😄

I actually think that the solution you're going for now is the only way around it. You could always wrap it inside a `Unboxer` extension that returns your type exactly (that would make it more specific and thus be picked by the compiler) to avoid the code being inside of your model (if you prefer).

I'm gonna think about this some more and see if I can come up with a solution, let me know if you do :)

**Comment by simme** [comment]
Awesome! :)

This will work just fine. Just not _as_ pretty as before ;) Type inference is beautiful until it isn't!
