### ISSUE TITLE
Xcode 8 beta 6 compatibility

### ISSUE THREAD

**Issue by ldiqual** [JohnSundell/Unbox#104]
@JohnSundell I converted the swift 3 codebase to the latest version (shipped with beta 6) on a local branch but I'm not sure how to handle the test migration.

Due to https://github.com/apple/swift-evolution/blob/master/proposals/0072-eliminate-implicit-bridging-conversions.md it's harder to create `[String: AnyObject]` with array literals because things like `47` are not implicitly convertible to `NSNumber` anymore. This is something that was looked into before implementing the proposal: https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20160502/016644.html

So for instance, the following code will not compile: https://github.com/JohnSundell/Unbox/blob/swift3/Tests/UnboxTests.swift#L93-L96 because `27` cannot be implicitly converted to `AnyObject` (here: `NSNumber`).

I'm not too sure how to work around this without a massive amount of boilerplate, like this:

```
[
    "dictionary" : [
        "FAIL" : 59 as NSNumber
    ] as [String: AnyObject]
]
```

Any idea?

**Comment by JohnSundell** [comment]
Hi @ldiqual, Unbox has now been updated to support Xcode 8 beta 6! :) `UnboxableDictionary` is now typed as `[String : Any]` to conform to the new implicit conversion rules.
