### ISSUE TITLE
Unboxing [NSURL]?

### ISSUE THREAD

**Issue by arsonik** [JohnSundell/Unbox#106]
Hi,
First, thanks for your amazing work !

Just wondering if that kind of unboxing is supposed to work:
```
struct Obj: Unboxable {
    let id: Int
    let pictures: [NSURL]?

    init(unboxer: Unboxer) {
        self.id = unboxer.unbox("id")
        self.pictures = unboxer.unbox("pictures")
```

where pictures is an array of strings

**Comment by clayellis** [comment]
Hi @arsonik! Welcome to Unbox! Glad to have you here! 

Yes, Unbox supports unboxing `NSURL`s from `String`s through the use of a transformer right out of the box! (No pun intended 😉) You should be good to go! Let us know if you have any other questions—we're always happy to help and we try to respond as quickly as possible!

**Comment by clayellis** [comment]
@JohnSundell I think we can close this one!

**Comment by arsonik** [comment]
hmm thanks for your reply,
doesn't seem to work right out of the box though
it is an array of NSURL ! to just a single NSURL is that why it's not working ?
not working ```self.pictures = unboxer.unbox("pictures_url")```
the code that is actually working:
```
        do {
            self.pictures = try Unboxer.performCustomUnboxingWithDictionary(unboxer.dictionary, closure: { unboxer in
                return (unboxer.dictionary["pictures"] as? [String])?.flatMap {
                    NSURL(string: $0)
                }
            })
        } catch {
            self.pictures = nil
        }
```

**Comment by clayellis** [comment]
@arsonik, I'll take a look in the morning. I know that there have been some issues in the past were arrays of transformables weren't unboxing quite as they should. Thanks for uncovering another case (if that is the case!) Just thought I'd chime in to let you know that you are indeed not crazy 😉

**Comment by ntnhon** [comment]
Hi guys, FYI I'm the one who opened #85 and got it compiled after the fix but it actually crashes in runtime.

**Comment by JohnSundell** [comment]
Hey @ntnhon, @clayellis, @arsonik! I see now that there's a bug in how an array of `UnboxableByTransform` values are handled (it just tries to unbox the same type, rather than going for the raw type and then transforming it). Will fix the bug now, stand by :)

**Comment by JohnSundell** [comment]
@ntnhon Shouldn't crash though, even with the current bug in the implementation. Can you post a stack trace?

**Comment by JohnSundell** [comment]
Fixed in `master`. Let me know how that works. Will make a release soon, probably tomorrow evening :)

**Comment by arsonik** [comment]
Working like a charm ! Thanks.

Stupid question: why unbox can't work with class i/o struct ?

**Comment by JohnSundell** [comment]
@arsonik Awesome 🎉 There's nothing preventing you to use classes instead of structs with Unbox. Just implement `init(unboxer:)` as a `required` initializer.

**Comment by arsonik** [comment]
My bad ! Dunno why I though I could not 👍🏻
