### ISSUE TITLE
Swift 3 documentation update (or function signature update)

### ISSUE THREAD

**Issue by kgaidis** [JohnSundell/Unbox#107]
Hi there, 

Just here to _document_ (pun intended) a documentation or style inconsistency due to Swift 3. 

Currently documentation states:
`let user: User = try Unbox(dictionary)`

But this is no longer true in Swift 3; it has to be:
`let user: User = try Unbox(dictionary: dictionary)`

Function:
`public func Unbox<T : Unboxable>(dictionary: UnboxableDictionary, context: Any? = default) throws -> T`

Thank you for the library!

**Comment by JohnSundell** [comment]
Hi @kgaidis! Yeah, you're right. All the APIs will be refined (and the documentation updated) with Unbox 2.0 in time for Swift 3. Will not do any work on it right now as Swift 3 is still somewhat in flux and bound to change, and since Unbox 2.0 will change the APIs to become more Swift 3 native. Will make sure to update the README on the Swift 3 branch with this information, so that it's clear :)

**Comment by andreyz** [comment]
@JohnSundell are you waiting for Swift 3.1?

**Comment by JohnSundell** [comment]
@andreyz Hehe no :) I guess I underestimated how many people would love to Swift 3 once the GM of Xcode 8 hits, so will prioritize this higher now (with the limited time that I have).

**Comment by andreyz** [comment]
It's a "turtles all the way down" problem, once your one project migrates to Swift 3, one would expect all depencies to migrate too. Hence the instense Swift 3 rush.

**Comment by JohnSundell** [comment]
It's on the top of my todo-list believe me. Would also love some help on this from you guys and the rest of the community. It's better to unblock yourself than having to wait IMO :)

**Comment by clayellis** [comment]
@JohnSundell I'll try to take some time on Saturday to start updating things if no one beats me to it. A little swamped until then, though.

**Comment by JohnSundell** [comment]
Finally I have time to do some work on this tomorrow - will keep you posted :)

**Comment by JohnSundell** [comment]
Ended up working mostly on Wrap for the last two evenings, since it didn't even compile for Swift 3. Now that's all done, and it's API has been refined - so will jump on this next 😅

**Comment by JohnSundell** [comment]
Since the documentation has now been updated (thanks @garnett) - this can be closed.

**Comment by JohnSundell** [comment]
Note though that the APIs will still be updated to be Swift 3 native in Unbox 2.0, which is being developed here: https://github.com/JohnSundell/Unbox/pull/126 😄
