### ISSUE TITLE
Array problem

### ISSUE THREAD

**Issue by dowhilenet** [JohnSundell/Unbox#11]
Hi, how to change an array to model
```JSON

data:

[
{"name":"tom"},
{"name":"li"},
.....
]
```

```swift
struct Name:Unboxable{
    let name:String
    init(unboxer: Unboxer) {
        name = unboxer.unbox("name")
    }
}

struct Names:Unboxable{
    let names:[Name]
    init(unboxer: Unboxer) {
        stares = unboxer.unbox("?????") 
    }
}
```

**Comment by JohnSundell** [comment]
Hi!

At the moment the main `Unbox` functions cannot return arrays, only nested arrays are supported, and the root JSON object needs to be a dictionary. However, I've had quite a lot of feedback about this, so I'm planning to add root array support in the next release of Unbox :)

In the meantime, if you have a root array in your JSON, you can use the following workaround:

```swift
struct Name: Unboxable {
    let name: String

    init(unboxer: Unboxer) {
        name = unboxer.unbox("name")
    }
}

struct Names: Unboxable {
    let names: [Name]

    init(unboxer: Unboxer) {
        self.names = unboxer.unbox("names") 
    }
}

let array: [AnyObject] = ...
let names: Names? = Unbox(["names" : array])
```

Will keep this issue open until root array support is implemented.

**Comment by dowhilenet** [comment]
Thank you! 

谢谢。

I very much look forward to the next version.

**Comment by JohnSundell** [comment]
Here we go! :) https://github.com/JohnSundell/Unbox/pull/12
