### ISSUE TITLE
How to catch errors in Swift 3

### ISSUE THREAD

**Issue by sp8hmz** [JohnSundell/Unbox#111]
My code is crashing when trying to unbox data fetched by Alamofire. How should I catch errors using do-catch in Swift 3?

**Comment by danielgalasko** [comment]
I think you need to do a bit more to help us help you @sp8hmz. There is more than enough information on how to do parsing using Unbox. Perhaps try and explain what the crash is and how you think Unbox might be responsible given that you have explicitly mentioned Alamofire. Seems to me (at a thumb suck) you are probably force unwrapping something i.e. `let x = json["key"] as! String` will cause a crash if the value can't be decoded to a String:)

**Comment by JohnSundell** [comment]
@sp8hmz  Are you able to provide any more information? :)

**Comment by JohnSundell** [comment]
Closing for now. @sp8hmz please let us know once you have some more actionable information.
