### ISSUE TITLE
Designated initializer cannot be declared

### ISSUE THREAD

**Issue by tcurdt** [JohnSundell/Unbox#115]
I was trying this (with swift3)

```
class Foo {
    init() {
    }
}

extension Foo: Unboxable {
    init(unboxer: Unboxer) {
      // Designated initializer cannot be declared in an extension of 'Foo';
      // did you mean this to be a convenience initializer?
    }
}
```

The only difference to my other code is that this is a `class` instead of a `struct`.

**Comment by JohnSundell** [comment]
@tcurdt In Swift, designated and required initializers can only be declared as part of a class definition, not as an extension, if that class is not marked as `final`. So you can either choose to make your class `final` or to move the conformance of `Unboxable` and its required `init` method into the declaration of your class, like this:

```
class Foo {
    init() {
       // Designated initializer
    }
    
    convenience init(unboxer: Unboxable) {
        self.init()
    }
}
```

**Comment by tcurdt** [comment]
So that really is because it's `class` instead of a `struct`.
I wasn't aware of that particular difference.
Thanks for clearing this up.

**Comment by JohnSundell** [comment]
No worries :)
