### ISSUE TITLE
Release new cocoapods version with swift 3 support

### ISSUE THREAD

**Issue by ldiqual** [JohnSundell/Unbox#118]
@JohnSundell Now that Xcode 8 is out, it would be awesome to have an official pod version with swift 3 support instead of relying on the `swift3` branch.

**Comment by JohnSundell** [comment]
Will do, as soon as the API has been refined to work well with Swift 3 and conform to all API guidelines. Will be done this week for sure.

**Comment by Ben305** [comment]
Has a release date already been selected?

**Comment by JohnSundell** [comment]
@Ben305 It's been delayed a bit due to me working on other open source projects and having limited time :/ Working on it today though! :)

**Comment by JohnSundell** [comment]
Hopefully I can get a verison released today!

**Comment by JohnSundell** [comment]
For those who are curious and want to follow the development of Unbox 2.0 (which will be the Swift 3 compatible release on CocoaPods + Carthage), check out this PR: https://github.com/JohnSundell/Unbox/pull/126

**Comment by bryanbartow** [comment]
Looks like #126 was merged. Does that mean an updated podspec is going to be published?

**Comment by JohnSundell** [comment]
@bryanbartow Give me a sec, gonna write the release notes. Will be published within 1 hour max :)

**Comment by bryanbartow** [comment]
@JohnSundell Nice!

**Comment by JohnSundell** [comment]
Aaaaaaand it's [RELEASED!](https://github.com/JohnSundell/Unbox/releases/tag/2.0) 🎉 🎉 🎉  Thank you so much for your patiance everyone, and hope that you like 2.0! 😄
