### ISSUE TITLE
Cocoapods with Swift 3 

### ISSUE THREAD

**Issue by serejahh** [JohnSundell/Unbox#119]
Hi, John. Thanks for the awesome lib!

I'm trying to update [UnboxedAlamofire](https://github.com/serejahh/UnboxedAlamofire) to swift 3. Unfortunately, cocoapods doesn't support specifying a branch in a podspec for dependencies. So, could you push a new podspec with swift 3? I suppose it can be `2.0`

**Comment by JohnSundell** [comment]
Duplicate of https://github.com/JohnSundell/Unbox/issues/118

**Comment by JohnSundell** [comment]
@serejahh Unbox 2.0 has now been released 🎉

**Comment by serejahh** [comment]
What a great news! Looking forward to update UnboxedAlamofire
