### ISSUE TITLE
Swift3 branch doesn't compile with xcode8 with swift3

### ISSUE THREAD

**Issue by alexs555** [JohnSundell/Unbox#120]
Hi! Did u try to compile latest swift3-branch version? I'm trying to use it, but can't even compile(
<img width="1388" alt="2016-09-26 15 22 14" src="https://cloud.githubusercontent.com/assets/3940001/18834267/a36c4956-83fd-11e6-884c-07ea2c033a53.png">
Any help would be appretiated

**Comment by clayellis** [comment]
Just out of curiosity, what happens when you force the `try` (`try!`)?

**Comment by alexs555** [comment]
"Use legacy swift version" option should be disabled in Unbox target inside Pods project and after that it compiles normally.
Cocoapods 1.1.0.rc.2 transfers parent's target settings to all pods, 1.0.1 doesnt.
