### ISSUE TITLE
Missing patch version from git tags (SPM)

### ISSUE THREAD

**Issue by DavidObfuscator** [JohnSundell/Unbox#132]
Swift Package Manager:
> The version requirements, which follow [Semantic Versioning (SemVer)](http://semver.org) conventions, are used to determine which Git tag to check out and use to build the dependency.

**Comment by JohnSundell** [comment]
@DavidObfuscator Ah, so I need to name releases `2.1.0` for example?

**Comment by DavidObfuscator** [comment]
yes, if you would like to support sift package manager

**Comment by JohnSundell** [comment]
@DavidObfuscator Will do that from now on, thanks! 👍

**Comment by aj1310** [comment]
Is the current release going to be tagged, or do we have to wait for a next one?

**Comment by JohnSundell** [comment]
Done! 😄 https://github.com/JohnSundell/Unbox/releases/tag/2.1.1. Will make sure to follow this convention in all releases going forward!
