### ISSUE TITLE
Cannot get UnboxRawValue = Double when implementing UnboxableByTransform

### ISSUE THREAD

**Issue by evgeniyd** [JohnSundell/Unbox#135]
I have an API which returns items in JSON. One item has a key `price_in_euros`:

    "price_in_euros": "38.88",

I'd like to transform it to `Price` object declared as 

    public struct Price {
        public var amount: Double
        public var currency: Currency
    }
    
    public enum Currency {
        case unspecified, euro
    }

In order to do so, I extend `Price` type conforming to `UnboxableByTransform` proto this way:

    extension Price: UnboxableByTransform {
        public typealias UnboxRawValue = Double
        
        init?(amount: Double) {
            self.currency = .euro
            self.amount = amount
        }
        
        public static func transform(unboxedValue: UnboxRawValue) -> Price? {
            return Price(amount: unboxedValue)
        }
    }

Unfortunately, during the testing, it results in error:

    Invalid Selection. [Unbox error] Invalid value found (38.88) for key "price_in_euros"

To workaround this issue I went with `UnboxRawValue` of `String`:

    extension Price: UnboxableByTransform {
        public typealias UnboxRawValue = String

        ...
    
        public static func transform(unboxedValue: UnboxRawValue) -> Price? {
            let value = Double(unboxedValue)
            return Price(amount: value!)
        }
    }

This works, but I'd like to know, whether it is something which is not supported by Unbox and thus has to be looked onto, or I'm doing something wrong here?

**Comment by JohnSundell** [comment]
Hey @evgeniyd! You're right in that you need the `UnboxRawValue` type of your `UnboxableByTransform` type to match the type you're expecting in your JSON. So in this case using `String` as your raw value is correct.

**Comment by evgeniyd** [comment]
@JohnSundell thank you very much!

I can confirm that if the API would return

    "price_in_euros": 38.88,

The `UnboxableByTransform` ext having

    public typealias UnboxRawValue = Double

...works perfectly.

**Comment by JohnSundell** [comment]
@evgeniyd Awesome 🎉
