### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by krystiansliwa** [JohnSundell/Unbox#139]
Does Unbox support linux machines?
Can I use it with Kitura framework and then run on linux machine?

**Comment by VivienGiraud** [comment]
I tried using cocoapods but it fails with:
`[!] The dependency ``Unbox`` is not used in any concrete target.`
Fair enough. So I tried by copy pasting the `Unbox.swift` file as I can see:
>#if !os(Linux)
>    import CoreGraphics
>#endif

At the beginning of the file.
But I get this:
<img width="866" alt="capture d ecran 2016-11-23 a 14 27 16" src="https://cloud.githubusercontent.com/assets/262924/20563459/0803bd1e-b189-11e6-936a-48d516b090d7.png">

**Comment by VivienGiraud** [comment]
Ok never mind, I was doing `pod install` in the wrong folder. I let my previous comment for posterity.
Anyway, it works with Pods!
It builds, then I will give it a try.
@krystiansliwa can you try it please?

**Comment by krystiansliwa** [comment]
On OSX it work as always but I am asking about plain linux platform.

**Comment by JohnSundell** [comment]
@krystiansliwa It should work on Linux (there have been contributors adding support to Linux in the past). If it doesn't, feel free to open issues and we'll fix it! 👍

**Comment by JohnSundell** [comment]
I don't have a Linux environment setup to test it on personally at the moment. Starting with Swift on Linux is still on my personal backlog 😅

**Comment by krystiansliwa** [comment]
If I have some free time I will check it on some of my Amazon EC2 Ubuntu instance. If works just add some info about it into documentation :)

**Comment by VivienGiraud** [comment]
I made so tries with my EC2 instance but as Swift doesn't support `NSURLSession`  I didn't manage to try `Unbox` .
But at least it compile.

**Comment by JohnSundell** [comment]
Since it compiles, and since there doesn't seem to be huge interest in Linux support, I'm going to close this for now. We can re-open later if this is something we want/need to address 🙂

**Comment by codeOfRobin** [comment]
@VivienGiraud On the contrary, `URLSession` works on Linux, just requires a custom session config (`URLSession.shared` is not implemented).
@JohnSundell Can confirm it works on Linux. Example project: https://github.com/codeOfRobin/UnboxExample

**Comment by JohnSundell** [comment]
@codeOfRobin That's awesome, thanks! 🚀
