### ISSUE TITLE
Do not understand  context

### ISSUE THREAD

**Issue by dowhilenet** [JohnSundell/Unbox#14]
我这些天在学习 `Unbox`，我有一个问题想请教你。`context: Any?`  是什么，有什么作用。我不太明白它是用来做什么的。

google translate:

These days I learn `Unbox`, I have a question to ask you. `context:? Any` What is, what role. I do not quite understand what it is to do.

Please give me an example, maybe I can understand  :)

**Comment by JohnSundell** [comment]
Sure! Unbox supports both optional and required contextual objects. These are objects that will be available during the unboxing process and can be used to make decisions when creating your model, inject dependencies, etc.

When your model conforms to `Unboxable`, a contextual object is always **optional**. If you pass one when starting the unboxing process using `Unbox()` or `UnboxOrThrow()`, it will be available on the `Unboxer` that gets passed into your model, like this:

```swift
struct MyModel: Unboxable {
     init(unboxer: Unboxer) {
          print(unboxer.context)
     }
}
```

If your model instead conforms to `UnboxableWithContext`, you can **require** that a contextual object of a certain type must be passed to begin the unboxing process. Like this:

```swift
struct MyModel: UnboxableWithContext {
     init(unboxer: Unboxer, context: [String]) {
          // The context can now be used, it's guaranteed to always be there
     }
}

let model: MyModel? = Unbox(data, context: ["1", "2", "3"])
```

More information can be found in the `README`:

"Sometimes you need to use data other than what's contained in a dictionary during the decoding process. For this, Unbox has support for contextual objects that can be made available on the `Unboxer` that is being used.

To pass a contextual object, use the `Unbox(dictionary:context:)` overload when you start the unboxing process.

The `Unboxer` passed to your `Unboxable`'s init method will then make your contextual object available through its `context` property.

You can also **require** that a contextual object is present during the unboxing process by using the `UnboxableWithContext` protocol. Types that conform to this protocol can then be unboxed using `Unbox(dictionary:context:)`, where `context` must be of the type’s defined `ContextType`."

**Comment by dowhilenet** [comment]
非常非常非常感谢你。我将会去实际的操作一下

Thank you very very much. I'll go look at the actual operation ：）
