### ISSUE TITLE
Use of unresolved identifier

### ISSUE THREAD

**Issue by paewel** [JohnSundell/Unbox#140]
Hello, 
When I add the Unbox.swift file to a new project I get:
![screen shot 2016-11-08 at 13 40 45](https://cloud.githubusercontent.com/assets/2945862/20099511/2029455c-a5b9-11e6-9cc1-c22af12ce5a1.png)

**Comment by slammed** [comment]
@paewel were you able to resolve this issue? I recently upgraded my project from iOS 8 (swift 2.2) to iOS 9.2 (swift 3). I am "trying" to use Unbox v2.2.0.

Any information is greatly appreciated.

**Comment by JohnSundell** [comment]
@paewel @serejahh Currently, it's not supported to use the file `Unbox.swift` directly in a project - you need to include Unbox as a library. This can be done either through a dependency manager like CocoaPods, Carthage or SPM, or by adding `Unbox.xcodeproj` as a dependency to your project manually.

Unbox will support using the Swift file directly again in an upcoming version, but when the move was made to Swift 3, different versions of the `unbox()` function/methods started colliding, meaning that `Unbox.unbox` needed to be added to resolve ambigiuity. Hope this helps 😄

**Comment by slammed** [comment]
Thank you for the reply @JohnSundell. I am pretty green when it comes to iOS dev, but I was able to get this imported via cocoapods through some brute force! Finally working!!

It might be worth mentioning that I now needed to add the "import Unbox" to all my swift files that used it.

Thank you once again!

**Comment by paewel** [comment]
Thank you for clarifying this :) And I can't wait for the upcoming version!

**Comment by JohnSundell** [comment]
Fixed in [Unbox 2.3](https://github.com/JohnSundell/Unbox/releases/tag/2.3.0). You can now use `Unbox.swift` directly again 🚀
