### ISSUE TITLE
Errors if key an underscore in it

### ISSUE THREAD

**Issue by tamutti** [JohnSundell/Unbox#143]
If you attempt to do like 

try unboxer.unbox(keyPath: "routes.overview_polyline.points")

It'll give error of

[UnboxError] An error occured while unboxing path "routes.overview_polyline.points": The key "overview_polyline" is missing.

yet in the JSON, the key does exist and is spelled correctly. Looks to error on the underscore.

**Comment by tamutti** [comment]
Problem looked to be that route is an array and you can't key path to an item in an array since it doesn't know which array item to look at.

**Comment by nikoagge** [comment]
So what's the solution to that problem?
