### ISSUE TITLE
Unbox(data: Data, keyPath: String) ?

### ISSUE THREAD

**Issue by frranck** [JohnSundell/Unbox#144]
Hello,
There is an Unbox(dictionary: UnboxableDictionary, keyPath: String) function, is there a reason why there is no such function with Data  as input in Unbox ?

PS: We wrote this patch in our code:
```
  public func Unbox<T: Unboxable>(data: Data, at key: String?) throws -> [T] {
      do {
          if let value = key {
              guard let json: UnboxableDictionary = try JSONSerialization.jsonObject(with: data, options: []) as? UnboxableDictionary else {
                  throw UnboxError.InvalidData
              }
              return try Unbox(dictionary: json, at: value)
          }
          return try Unbox(data: data, allowInvalidElements: true)
      } catch {
          throw UnboxError.InvalidData
      }
  }
```

**Comment by JohnSundell** [comment]
Hi @frranck, sounds like a great addition to the API! Want to contribute it as a PR? 😃 (if you do, please make sure that the signature of the method follows the convention set by the other `unbox()` functions).

**Comment by JohnSundell** [comment]
Implemented in [Unbox 2.3](https://github.com/JohnSundell/Unbox/releases/tag/2.3.0).

**Comment by frranck** [comment]
@JohnSundell  thanks a lot

**Comment by frranck** [comment]
PS: do you plan to use swift3 for master ? seems the swift3 branch did not get updated.

**Comment by JohnSundell** [comment]
@frranck No problems 👍 `master` already uses Swift 3, since `2.0`. The Swift 3 branch is only left in case someone was still using it. Will probably delete in a month or so.
