### ISSUE TITLE
Unable to add import "Unbox"

### ISSUE THREAD

**Issue by laiqahmed440** [JohnSundell/Unbox#147]
I have installed the pod file after adding unbox in it. But, when ever I wrote import "Unbox" in ti my swift file, I got the following error: Unable to find module "Unbox". Can somebody help me in fixing this issue.

**Comment by JohnSundell** [comment]
@laiqahmed440 Can you verify that Unbox is a part of your workspace, that it is included in `Target Dependencies`, `Link Binary With Libraries` and `Embed Frameworks` in your project's `Build Phases`?

**Comment by laiqahmed440** [comment]
I have only add Unbox pod in the Podfile and and install it from the terminal. After that I have included import Unbox in my class which is producing errors. Are there any more steps which I have to follow?

**Comment by laiqahmed440** [comment]
Can you please share me the complete procedure of linking Unbox with my project?

**Comment by JohnSundell** [comment]
@laiqahmed440 Please refer to CocoaPods' documentation on how to include Pods in your project.
