### ISSUE TITLE
Unbox root dictionary with unknown keys

### ISSUE THREAD

**Issue by mislavjavor** [JohnSundell/Unbox#148]
The `unbox()` function doesn't support trivial unboxing of root dictionaries with unknown keys

For example:
```json
{
    "212" : { ... unboxable object ... },
    "645" : { ... unboxable object ... }
}
``` 

"212" and "645" are not known at compile time. 

What I expected was an `unbox()` function with a return type `[String: Unboxable]` so I could do

`let model : [String: SomeUnboxable] = try unbox(data: responseData)`

Is there some way to implement this?

**Comment by SanjithKanagavel** [comment]
@ JohnSundell Is this possible with the current version ?

**Comment by clayellis** [comment]
I would serialize the response JSON into a `[String: Any]` as `responseJSON` and then do something like:
```swift
for key in responseJSON.keys {
    do {
        let model: YourUnboxableModel = try unbox(dictionary: responseJSON, atKey: key)
        // Do something with your model
    } catch {
        // Log the error
        continue
    }
}
```
Of course, that does assume that your response JSON has the "unknown" keys at the root of the object.

**Comment by clayellis** [comment]
On second thought, looks like @JohnSundell has a more "unbox-y" answer over on https://github.com/JohnSundell/Unbox/issues/146
Take a look at that as well.

**Comment by JohnSundell** [comment]
Yes, exactly what @clayellis says, I'd follow the exact same approach as outlined in #146

**Comment by JohnSundell** [comment]
Closing this one as a duplicate.
