### ISSUE TITLE
Multiple DateFormatters

### ISSUE THREAD

**Issue by benediktreichert** [JohnSundell/Unbox#149]
Hi,

I need to parse multiple time representations coming from JSON. A `DateFormatter()` instance can only parse one date representation provided on the `dateFormat` property. So I need multiple DateFormatter instances. I can only provide one DateFormatter instance to Unboxer however 😞.

I have done a very dirty workaround with nested try-catch clauses, when the first DateFormatter can not parse the date representation, the next DateFormatter in the catch clause will try, if this fails, I throw. I am not content with this workaround and I would appreciate any tip if there is a more elegant way.

Here is the code, please note the nested try-catch DateFormatter section.
```swift
convenience init(unboxer: Unboxer) throws {
		self.init()
		self.id = try unboxer.unbox(key: "id")
		
		do {
			// Backend Date Format
			let dateFormatter = DateFormatter()
			dateFormatter.dateFormat = "yyyy-MM-dd'T'HH:mmx"
			self.date = try unboxer.unbox(key: "date", formatter: dateFormatter)
		} catch {
			// Mock API Date Format
			let dateFormatter = DateFormatter()
			dateFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSz"
			self.date = try unboxer.unbox(key: "date", formatter: dateFormatter)
			// Throw error if we can not parse any of both date formats
			// ...
		}
		

		self.subject = try unboxer.unbox(key: "title")
		self.body = try unboxer.unbox(key: "text")
		self.author = try unboxer.unbox(key: "author")
		self.isMoodle = try unboxer.unbox(key: "moodle")
	}
```

**Comment by JohnSundell** [comment]
How about making your own `UnboxFormatter` that takes an array of `DateFormatters` and tries each one, or returns nil?

For example:

```swift
class ComposedDateFormatter: UnboxFormatter {
    private let dateFormatters: [DateFormatter]

    init(dateFormatters: [DateFormatter]) {
        self.dateFormatters = dateFormatters
    }
 
    func format(unboxedValue: String) -> Date? {
        for formatter in dateFormatters {
            if let date = formatter.date(from: unboxedValue) {
                return date
            }
        }

        return nil
    }
}
```

**Comment by JohnSundell** [comment]
@benediktreichert Does the above solution work for you?

**Comment by benediktreichert** [comment]
Sorry for the late response! The solution is perfectly fine, I am a bit ashamed that I did not come up with it.
From a framework user view, parsing dates may be such a common task you might consider including it in Unbox without the need of creating an own parser implementation, anyway, I consider this issue closed, may it be helpful to others seeking how to parse multiple dates :-)
