### ISSUE TITLE
Unbox/Wrap anything

### ISSUE THREAD

**Issue by Czajnikowski** [JohnSundell/Unbox#150]
Hi!

I like the simplicity of the API, error handling and type inference at work here. I like the name as well - what I like about it is that it's not limiting to JSON only 😃  My idea is - how about adding support for MessagePack, Plist or other kind of things? I can even find some time in my spare time to help you.

Cheers!

**Comment by JohnSundell** [comment]
Thanks for the suggetion @Czajnikowski! I'd like to limit Unbox & Wrap's scopes to handling JSON only - JSON alone as a lot of edge cases that need to be supported, so handling all those other file formats would significantly increase the size and complexity of the libraries - I'd like to keep them as small as possible for maintainability 🙂
