### ISSUE TITLE
When using keypath on empty/nil throws error

### ISSUE THREAD

**Issue by tamutti** [JohnSundell/Unbox#154]
If you attempt to do something like

self.item1 = try unboxer.unbox(keyPath: "i.item1")
self.item2 = try unboxer.unbox(keyPath: "i.item2")

and if i.item1 doesn't exist or it it nil, it will stop and not proceed to item2. To me it should return the default value of what it is you are trying to unbox as defined in the struct or let it be able to be set and not error since erring causes it to exit and not move to the next item.

To resolve this have to wrap everything in a do/catch.

**Comment by clayellis** [comment]
@tamutti I understand what you're saying about returning default values, but that could have some unintended repercussions in a lot of different scenarios. What if the JSON was invalid or malformed and you tried to unbox your object from it? Should it just create a fully initialized object with default values or should it warn you about the invalid JSON? 

Luckily, @JohnSundell considered these scenarios and included two features in Unbox to work through them (two that I can think of, anyways.)

1. Make `item1` optional and initialize it with a default value.

```
struct Foo {
   let item1: Int? = 0
   let item2: Int
}

extension Foo: Unboxable {
    init(unboxer: Unboxer) throws {
        self.item1 = try? unboxer.unbox(keyPath: "i.item1")
        self.item2 = try unboxer.unbox(keyPath: "i.item2")
    }
}

With JSON:
{
    i: {
        item2: 5
    }
}
```

... will result in `Foo.item1 = Optional(0)` and `Foo.item2 = 5`.

You're probably saying, "well I don't want `item1` to be an Optional." I wouldn't either. That's where solution two comes in.

2. Use `if let _ try?` to check for the existence of the `keyPath` and fallback if needed

```
struct Foo {
   let item1: Int
   let item2: Int
}

extension Foo: Unboxable {
    init(unboxer: Unboxer) throws {
        if let item1: Int? = try? unboxer.unbox(keyPath: "i.item1") {
            self.item1 = item1
        } else {
            self.item1 = 0 // You choose the default value
        }
        self.item2 = try unboxer.unbox(keyPath: "i.item2")
    }
}
```

Now if `i.item1` doesn't exist, you can choose and set the default value yourself. This way every scenario is managed; errors are thrown by default to warn against invalid JSON, and you can short-circuit unboxing on a case-by-case basis when a key is missing.

Hope this helps! Feel free to ask any questions about the code above!

**Comment by tamutti** [comment]
Thanks for the details on this. Unfortunately, scenario 2 raises all kinds of errors if it doesn’t exist. Only solution that has worked was to actually wrap in a do/catch. The try will throw errors in its attempt to unwrap an optional since it doesn’t exist in the json. I know you wouldn’t think so since its general swift code but it is in my case.

Micah

**Comment by clayellis** [comment]
Actually, if you mark `try` as optional, (like so `if let item1 = try? unbox...` where `try*?*` is key) then you don't need to deal with `do try catch` blocks.

**Comment by clayellis** [comment]
From Apple's Swift Documentation. [Error Handling > Handling Errors > Converting Errors to Optional Values](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/ErrorHandling.html)

> You use try? to handle an error by converting it to an optional value. If an error is thrown while evaluating the try? expression, the value of the expression is nil. Using try? lets you write concise error handling code when you want to handle all errors in the same way. For example, the following code uses several approaches to fetch data, or returns nil if all of the approaches fail.

**Comment by tamutti** [comment]
Retried but you get errors even in attempts like you posted on

 if let item1: Int? = try? unboxer.unbox(keyPath: "i.item1") {

            self.item1 = item1

        } else {

            self.item1 = 0 // You choose the default value

        }

        self.item2 = try unboxer.unbox(keyPath: "i.item2")

fatal error: unexpectedly found nil while unwrapping an Optional value

self.item1 = item1 has to be unwrapped so the correct syntax is self.item1 = item1! but it'll throw an error. Therefore, the only way to resolve this it to use to use a do/catch.

**Comment by clayellis** [comment]
Try this:

`if let item1: Int = try? unboxer.unbox...` 

instead of:

`if let item: Int? = try? unboxer.unbox...`

You need to unbox an `Int` not an `Int?`.

**Comment by tamutti** [comment]
That’ll work but you are going to get all kinds of warnings from Xcode about

No calls to throwing functions occur within ‘try’ expression.

Would be better to not have those thrown to satisfy a default.

**Comment by clayellis** [comment]
@tamutti Would you mind posting your code? Because I'm doing exactly what I've outlined above without any warnings. Sounds like you're getting something confused.

**Comment by JohnSundell** [comment]
Actually, you shouldn't use `try?` in case of an optional value, simply remove the try and Swift will automatically dispatch to the correct overload of `unbox()` and no error will be thrown in case the value was missing or invalid. Here's an example:

```swift
struct MyModel {
    let required: String
    let optional: String?
}

extension MyModel: Unboxable {
    init(unboxer: Unboxer) {
        required = try unboxer.unbox(key: "required")
        optional = unboxer.unbox(key: "optional")
    }
}
```

Check out "Advanced Example" in the README that demonstrates this mechanic.

**Comment by tamutti** [comment]
This was the solution. Thanks a bunch.

**Comment by JohnSundell** [comment]
No problems @tamutti! 👍

**Comment by nikoagge** [comment]
Well I show and tried your proposals but with no luck. Actually my problem is that my data is complex so I use keyPath but I don't know what to do when keyPath is missing.
