### ISSUE TITLE
Unbox ignores error if no value in required fields even if they are many levels deep inside an optional

### ISSUE THREAD

**Issue by AlexanderNorway** [JohnSundell/Unbox#155]
I have been using unbox for a long time now and I stumbled upon something kinda strange.

I have a `User` object that contains an optional array `lists`. Even if the `lists` array gets a value it will just get set to `nil` if one of the objects within objects further down is `required` and has `no value`. 
This is somewhat expected behavior for Unbox, however I want it to throw all the way up to where we create the user so that I can know that it actually failed to parse an expected value in a `required` field. It of course doesn't do that because of the optional `lists` array on the root object. As is, I have no way of knowing what failed and that it didn't just return a `User` with no lists if the required `data` field in `ListData` doesn't get a value.

JSON:
```
{
  "userId": "123",
  "lists": [
    {
      "list_id": "String",
      "list_data": {
        "type": "String",
        "subtype": "String",
        "data": {
          "field": "String"
        }
      }
    }
  ]
}
```

Code:
```
struct User {
    let userId: String
    let lists: [List]?
}

extension User: Unboxable {
    init(unboxer: Unboxer) throws {
        self.userId = try unboxer.unbox(key: "userId")
        self.lists = unboxer.unbox(key: "lists")
    }
}

struct List {
    let listId: String
    let listData: [ListData]
}

extension List: Unboxable {
    init(unboxer: Unboxer) throws {
        self.listId = try unboxer.unbox(key: "list_id")
        self.listData = try unboxer.unbox(key: "list_data")
    }
}

struct ListData {
    let type: String
    let subType: String
    let data: ListMetaData
}

extension ListData: Unboxable {
    init(unboxer: Unboxer) throws {
        self.type = try unboxer.unbox(key: "type")
        self.subType = try unboxer.unbox(key: "sub_type")
        self.data = try unboxer.unbox(key: "data")
    }
}

struct ListMetaData {
    let field: String
}

extension ListMetaData: Unboxable {
    init(unboxer: Unboxer) throws {
        self.field = try unboxer.unbox(key: "field")
    }
}
```

Changing the `lists` array to `required` would fix the problem as it then would `throw` all the way up, but what about the cases where the outer value has to be optional.

I prefer not to do manual checks if the parser could do it for me.

Any suggestions or explanations on why it has to be like this?

**Comment by JohnSundell** [comment]
Hi @AlexanderNorway! You can use `allowInvalidElements: true` when unboxing the `lists` array, that way Unbox will automatically ignore any invalid elements in the array, without rendering the entire array invalid. Would that work for you?

**Comment by AlexanderNorway** [comment]
It`s kinda the opposite of what I want. I want it to just fail if a required field is missing even if inside an optional. I want to catch the error when crating the user object.

**Comment by JohnSundell** [comment]
Ah, now I understand. How about this:

```swift
struct User {
    let userId: String
    let lists: [List]?
}

extension User: Unboxable {
    init(unboxer: Unboxer) throws {
        self.userId = try unboxer.unbox(key: "userId")
        
         do {
             self.lists = try unboxer.unbox(key: "lists")
         } catch {
             // Error handling
         }
    }
}
```

**Comment by AlexanderNorway** [comment]
No calls to throwing functions occur within `try` expression. 
`catch` block is unreachable because no errors are thrown in `do` block.

**Comment by JohnSundell** [comment]
@AlexanderNorway Ah sorry, my bad - that's what I get for writing code directly in the GitHub editor 😝 Updated my comment above, take a look.

**Comment by AlexanderNorway** [comment]
Hehe, your last edit still gave a compilation error because the initializer returned without initializing all stored properties. 😝

I understood your solution though. For my use case I didn't need the try catch for `lists` as I want to handle it in the try catch I use to make the User object.

```
extension User: Unboxable {
    init(unboxer: Unboxer) throws {
        self.userId = try unboxer.unbox(key: "userId")
        let lists: [List] = try unboxer.unbox(key: "lists")
        self.lists = lists
    }
}
```

Works perfectly. Thanks!

**Comment by JohnSundell** [comment]
Right, it was meant as an example, not the whole thing 😄
Perfect, happy that we found a solution! Closing this now 🚀

**Comment by AlexanderNorway** [comment]
Hi. I probably should have testet a little more thorough on a Friday. 
The result of my code above will basically just turn the lists property into a required, which won't work for my case as it may or may not exist.
Any suggestions? :)

**Comment by JohnSundell** [comment]
Alright, so - to list the requirements:

1) If there's no `list` field the parsing for `User` shouldn't fail, it should simply result in a `lists = nil`.
2) If there _is_ a `list` field, it should basically be treated as a required property - in that any invalid element in the `lists` array should make the parsing fail for `User`.

This code should fulfill both of those requirements:

```swift
extension User: Unboxable {
    init(unboxer: Unboxer) throws {
        self.userId = try unboxer.unbox(key: "userId")
        
        if let listDictionaries: [UnboxableDictionary] = try? unboxer.unbox(key: "lists") {
            self.lists = try listDictionaries.map(unbox)
        } else {
            self.lists = nil
        }
    }
}
```

Basically, you need to first check if there's any data for the key `lists` before attempting to parse it.
