### ISSUE TITLE
Unbox + Realm native “List” object

### ISSUE THREAD

**Issue by mhergon** [JohnSundell/Unbox#156]
I'm trying to use `Unbox` to make `Realm` object with other related objects inside using `List`. The `JSON` response from server has this structure.

    [
      {
        "name": "bla bla",
        "desc": "bla bla",
        "sequential": true,
        "createdAt": "2017-01-23T09:58:05.095Z",
        "hmImages": [
          {
            "urlBase": "https://blabla.com",
            "fullresPath": "/blaPath/iyba783fR81L8y.jpg",
            "id": "bla bla"
          },
          {
            "urlBase": "https://blabla.com",
            "fullresPath": "/blaPath/iyba783fR81L8y.jpg",
            "id": "bla bla"
          }
        ],
        "tags": [],
        "id": "bla bla"
      },
      {
        "name": "bla bla",
        "desc": "bla bla",
        "sequential": true,
        "createdAt": "2017-01-23T09:58:05.095Z",
        "hmImages": [
          {
            "urlBase": "https://blabla.com",
            "fullresPath": "/blaPath/iyba783fR81L8y.jpg",
            "id": "bla bla"
          }
        ]
        "tags": [],
        "id": "bla bla"
      }
    ]

Note that root object is an `Array` of dictionaries. Every dictionary has an `Array` of image dictionaries.

The class to save objects in `Realm` looks like this:

    // MARK: - Realm
    final class Challenge: Object {
        
        dynamic var id = ""
        dynamic var name = ""
        dynamic var desc = ""
        dynamic var sequential = false
        dynamic var createdAt = Date()
        dynamic var btPlayground = ""
        
        // Relations
        let hmImages = List<Image>()
        let tags = List<Tag>()
        
        override static func primaryKey() -> String? {
            return "id"
        }
        
    }
    
    // MARK: - Unboxable
    extension Challenge: Unboxable {
        
        convenience init(unboxer: Unboxer) throws {
            self.init()
  
            // Date formatter
            let dateFormatter = ISODateFormatter()
            
            id = try unboxer.unbox(key: "id")
            name = try unboxer.unbox(key: "name")
            desc = try unboxer.unbox(key: "desc")
            sequential = try unboxer.unbox(key: "sequential")
            createdAt = try unboxer.unbox(key: "createdAt", formatter: dateFormatter)
            btPlayground = try unboxer.unbox(key: "btPlayground")
            
        }
        
    }

The problem occurs with `hmImages` keypath. `Unbox` can't parse automatically and I need a way to do this.

I tried `UnboxableByTransform` with something like this:

    extension List<T>: UnboxableByTransform {
    
        public typealias UnboxRawValue = [[String:Any]]
        
        public static func transform(unboxedValue: Array<[UnboxableDictionary]>) -> List<T>? {
     
            
        }
        
    }

but didn't work.
Any idea?

Thanks!

**Comment by JohnSundell** [comment]
Hi @mhergon! Since there's no guarantee that the elements that `List` contains are unboxable, there's no simple way to add `UnboxableByTransform` support using an extension (since you can't - as of Swift 3.0 - limit protocol conformance with a generic constraint). What I'd do instead, is to write an extension on `Unboxer` that produces a `List<T>`, like this:

```swift
extension Unboxer {
    func unbox<T: Unboxable>(key: String) throws -> List<T> {
        let list = List<T>()
        
        let items: [T] = try unbox(key: key)
        
        for (index, item) in items.enumerated() {
            list[index] = item
        }
        
        return list
    }
}
```

Would that work for you?

**Comment by mhergon** [comment]
Works fine!
Thanks!

**Comment by shekibobo** [comment]
What does your `init(unboxer: Unboxer)` method end up looking like for this? I can't write to the property because it's already initialized and it's a `let`. Seems like you'd have to initialize a variable in the initializer and add the items to the property instance of the list.

**Comment by tymphillips** [comment]
@JohnSundell Would that extension be any different for keyPath?
