### ISSUE TITLE
Two minor proposals

### ISSUE THREAD

**Issue by Avtolic** [JohnSundell/Unbox#158]
Hello! Thank you for Unbox - it is great!
I have two proposals/questions:
1. I think it will be good to mention UnboxFormatter protocol in a readme. It is an important feature and it should be in the docs. Now there is no information about custom formatters except DateFormatter. 
2. Do you plan to add some short form of most used `unbox(key:)` method like some other libs do. Compare:
```
// Unbox, Gloss, Mappable
age = unboxer.unbox(key: "age") 
age = "age" <~~ json
age <- map["age"] 

```
Thank you

**Comment by JohnSundell** [comment]
Hi @Avtolic! Thanks for your proposals! 🎉 Added an example on how to use `UnboxFormatter` here: https://github.com/JohnSundell/Unbox/commit/352982b274180eebddc628c914abafe37f88444c

As for operator overloads, there are no plans to add them to Unbox at this point. They can easily be added in an extension, however, for developers that prefer this type of syntax (I'm not one of them 😅)

Closing this issue now, feel free to open more issues if you have more proposals! 🚀
