### ISSUE TITLE
Decimal unbox support from number

### ISSUE THREAD

**Issue by bencallis** [JohnSundell/Unbox#159]
Currently unbox supports transforming to the `Decimal` type for string values, but it does not support transformation from numbers.

The advantage of using this over `Double` would be to allow us to do more accurate numeric operations on these values.

Something like this should work? Let me know your thoughts. If you are happy I will open a PR.

```
extension Decimal: UnboxableRawType {
    public static func transform(unboxedNumber: NSNumber) -> Decimal? {
        return Decimal(string: unboxedNumber.stringValue)
    }

    public static func transform(unboxedString unboxedValue: String) -> Decimal? {
        return self.init(string: unboxedValue)
    }
    
}
```

**Comment by JohnSundell** [comment]
Sounds great to me - feel free to make `Decimal` conform to `UnboxableRawType`! 👍

**Comment by bencallis** [comment]
Thanks @JohnSundell . PR open https://github.com/JohnSundell/Unbox/pull/161 . We may want to squash the 2 commits during merge.

**Comment by JohnSundell** [comment]
Implemented in https://github.com/JohnSundell/Unbox/pull/161
