### ISSUE TITLE
Example for unboxing date property

### ISSUE THREAD

**Issue by shsteven** [JohnSundell/Unbox#16]
Hi John,

Thank you for creating this wonderful library!

Can you please provide an example for unboxing date strings?

**Comment by JohnSundell** [comment]
Hi Steven,

Happy you like Unbox :)

I was writing an example, but then realized it's about time that Unbox got built-in support for `NSDate` (the number 1 feature request currently) - so, here we go: 
https://github.com/JohnSundell/Unbox/commit/3c145600a6bd6f7dcca369c57c0d3bd0ce46bc8b

:rocket:

**Comment by shsteven** [comment]
My favorite object mapping lib just got better!

**Comment by JohnSundell** [comment]
:D
