### ISSUE TITLE
Unbox directly to String

### ISSUE THREAD

**Issue by bjarkehs** [JohnSundell/Unbox#162]
Is it possible to unbox directly to `String`? I can't seem to figure out how.

I'm using something like https://github.com/RyogaK/Moya-Unbox, but one response is just a simple `String` object.

**Comment by JohnSundell** [comment]
Do you simply want to turn `Data` into a `String`? If so then you don't need a JSON decoder, you can just use the standard library:

```swift
let string = String(data: data, encoding: .utf8)
```

If we're talking about a string as a property of a model, decoded from JSON, then you'd use Unbox like this:

```swift
struct Model: Unboxable {
    let string: String

    init(unboxer: Unboxer) throws {
        string = try unboxer.unbox(key: "string")
    }
}
```

Does any of the above solve your issue?

**Comment by bjarkehs** [comment]
Well, basically I have some data that returns a token. So like:

```json
{
    "token": "best-token-ever",
    "other-property": { ... }
}
```

Say I just want a shorthand to get the `token` of my data. Then I'd first have to decode and then get the `String`. I found a solution for now using `Unboxer` from `Data` and then unboxing like within a model.

Basically I'd like to avoid needing a model just to unbox a single `String` element at a given key. Does it make sense what I'm trying to achieve?

**Comment by JohnSundell** [comment]
Yeah that sounds like a good solution, create an Unboxer, then get the `token` string from there! 👍 Then you don't need a model. Can this be closed then?

**Comment by bjarkehs** [comment]
Yep! 👍
