### ISSUE TITLE
How to use with subclasses?

### ISSUE THREAD

**Issue by christopherpow** [JohnSundell/Unbox#166]
Say I have the (somewhat hypothetical) following example:

```swift
class Level
{
  var platforms: [Platform]
}

class Platform
{
   var pos: CGPoint
   var extent: CGFloat
}

class SlipperyPlatform: Platform
{
  var friction: CGFloat
}

class MovingPlatform: Platform
{
  var velocity: CGVector
}

And lets say I have the following (somewhat hypothetical) JSON:

{ "level":
  { "platforms":
    [ { "pos": .., "extent": .., "friction": .. },
      { "pos": .., "extent": .., "velocity": .. },
..
```

Perhaps its simple and I'll figure it out, but was just looking through the README for a quick example and didn't find one. Thanks for this wonderful set of packages!

**Comment by christopherpow** [comment]
More information:
I added the suggested debugging tip to the unbox catch and discovered that my problem is because my type needs to be UnboxableWithContext so I can pass context (obviously...). But collection types don't support this? Only Unboxable?

**Comment by christopherpow** [comment]
The remaining part being that my array of superclass objects only unboxes as high as the superclass...so Platform unbox initializer is called for all platform objects.

**Comment by JohnSundell** [comment]
So, just to make sure I understand the question, you want to dispatch to different subclasses of `Platform` depending on whether the `friction` or `velocity` key is in the JSON?

**Comment by christopherpow** [comment]
That was my thinking, yes.

**Comment by christopherpow** [comment]
Any thoughts on this yet? Also I wonder if you could clarify the custom unboxing example. By itself it's not making much sense.

**Comment by JohnSundell** [comment]
So this is basically the same problem as discussed in https://github.com/JohnSundell/Unbox/issues/171 (and other issues).

You're looking to dispatch to different implementations of the `Unboxable` protocol depending on the type. You use the custom Unboxing API to achieve this, like this:

```swift
// First, we need to make CGVector unboxable
extension CGVector: Unboxable {
    public init(unboxer: Unboxer) throws {
        dx = try unboxer.unbox(key: "dx")
        dy = try unboxer.unbox(key: "dy")
    }
}

class Level: Unboxable {
    var platforms: [Platform]

    required init(unboxer: Unboxer) throws {
        let dictionaries: [UnboxableDictionary] = try unboxer.unbox(keyPath: "level.platforms")

        // Use the custom unboxing API to dispatch to different Platform subclasses
        platforms = try Unboxer.performCustomUnboxing(array: dictionaries) { unboxer in
            if let friction: CGFloat = unboxer.unbox(key: "friction") {
                return SlipperyPlatform(friction: friction)
            }

            return try MovingPlatform(velocity: unboxer.unbox(key: "velocity"))
        }
    }
}
```

**Comment by JohnSundell** [comment]
I'm going to add an example like this ☝️ to the README, since this is a quite commonly asked question 😄

**Comment by christopherpow** [comment]
Thanks John. That was what I was hoping for. It just wasn't clear to me from the existing example in the README how the custom unboxing could be used for my purpose. I suppose the same approach could be used if I had a "type" key in each platform object...instead of having to figure out what type it was by what keys were or weren't present. Still loving this package!

**Comment by JohnSundell** [comment]
@christopherpow yeah exactly, a `type` key is a very common way to represent polymorphism in JSON 👍 but your approach is just as valid I think. Happy you like Unbox! 🙂
