### ISSUE TITLE
Unboxing an optional value does not throw.

### ISSUE THREAD

**Issue by tzaid** [JohnSundell/Unbox#167]
Unboxing an optional value does not throw. The presence of a value during unboxing should not guarantee its validity. Consider the following structure:

```Swift
struct User: Unboxable {
  var id: String
  var profile: Profile?

  init(unboxer: Unboxer) throws {
    self.id = try unboxer.unbox(key: "id")
    self.profile = unboxer.unbox(key: "profile")
  }
}

struct Profile: Unboxable {
  var name: String
  var age: Int

  init(unboxer: Unboxer) throws {
    self.name = try unboxer.unbox(key: "name")
    self.age = try unboxer.unbox(key: "age")
  }
}
```

Unboxing the json structure below should throw. Instead it swallows the missing `"age"` key error.

```json
{
  "id": "12345",
  "profile": {
    "name": "John Appleseed"
  }
}
```

Do you think this is something worth changing in the release targeting Swift 3.1 since it will break API?

**Comment by tzaid** [comment]
You can still achieve the current optional unboxing functionality with `try?`. Although it would need to appear in the model's unbox initializer.

**Comment by JohnSundell** [comment]
This is behaving as intended. If the property (in this case `profile`) is not required, Unbox will not throw if the value is missing/invalid. In order to make `profile` required and enable Unbox's throwing behavior, simply make the property non-optional.

**Comment by JohnSundell** [comment]
Closing this for now. Let me know if you need any additional support 🙂

**Comment by tzaid** [comment]
Thanks for the reply!

Does the intended behaviour make sense though? If the property is not required, shouldn't the Unboxer:
* return `.none` if the key is missing.
* return `.some` if the key is present and unboxing succeeds
* throw if unboxing fails

Right now there is no way to differentiate between the absence of a value and a failure while unboxing when using the optional method overloads.

A developer can still use current optional behaviour by using `try?`.
