### ISSUE TITLE
Mapping empty string to nil

### ISSUE THREAD

**Issue by lzell** [JohnSundell/Unbox#173]
Great library! Is there a recommended approach in place for informing Unbox that all zero-length strings should be transformed to nil?

Here's a test that shows exactly what I mean:
https://github.com/lzell/Unbox/commit/7e0d81c0e3118f316c733f98f6204b15a82c5843

**Comment by JohnSundell** [comment]
Hi @lzell, happy you like Unbox 😄 I'd recommend using an extension on `Unboxer` to implement this behavior in your app. For example:

```swift
extension Unboxer {
    func unboxNonEmptyString(forKey key: String) throws -> String {
        let string = try unbox(key: key) as String
        
        guard string.characters.count > 0 else {
            throw UnboxPathError.invalidValue(string, key)
        }

        return string
    }
}
```

**Comment by lzell** [comment]
Worked Great! Thanks :)

**Comment by JohnSundell** [comment]
👍
