### ISSUE TITLE
Direct use of "Unboxer" object

### ISSUE THREAD

**Issue by christianselig** [JohnSundell/Unbox#177]
99% of the time I use Unboxer, I use it by having an object extend `Unboxable`. But every so often I won't need a full fledged model object for a small URL extraction. 

Is it okay to directly initializer `Unboxer()`?

In the case of just wanting to grab a URL, if I try something like:

```` swift
let url: URL = try unbox(dictionary: jsonDict, atKey: "important_url")
````

I get the delightful `Ambiguous reference to member 'unbox(dictionary:)'` compile-time error.  It's easy enough to do with directly initializing a separate `Unboxer` object, though:

````swift
let unboxer = Unboxer(dictionary: jsonDict)
let url: URL = unboxer.unbox(key: "important_url")
````

Is that okay to be doing? If so, say I have JSON where the root is an array, such as the following:

````json
[
    {
        "description": "A first impression of Los Angeles as a struggling waiter in a world of wealth and coldness.  I made this film to remember those times.",
        "duration": 325,
        "embed_privacy": "anywhere",
        "height": 1080,
        "id": 211513023,
        "stats_number_of_comments": 20,
        "stats_number_of_likes": 349,
        "stats_number_of_plays": 250,
        "tags": "",
        "thumbnail_large": "https://i.vimeocdn.com/video/627559208_640.webp",
        "thumbnail_medium": "https://i.vimeocdn.com/video/627559208_200x150.webp",
        "thumbnail_small": "https://i.vimeocdn.com/video/627559208_100x75.webp",
        "title": "Service",
        "upload_date": "2017-04-04 12:03:13",
        "url": "https://vimeo.com/211513023",
        "user_id": 16243544,
        "user_name": "Josh Shaffner",
        "user_portrait_huge": "https://i.vimeocdn.com/portrait/8768265_300x300.webp",
        "user_portrait_large": "https://i.vimeocdn.com/portrait/8768265_100x100.webp",
        "user_portrait_medium": "https://i.vimeocdn.com/portrait/8768265_75x75.webp",
        "user_portrait_small": "https://i.vimeocdn.com/portrait/8768265_30x30.webp",
        "user_url": "https://vimeo.com/joshshaffner",
        "width": 1920
    }
]
````

(From Vimeo)

How would I initialize custom `Unboxer` object with that, given that `Unboxer` seemingly doesn't have an initializer for an array of dictionaries?

Great library by the way, looking forward to 3.0!

**Comment by JohnSundell** [comment]
Sure thing, you can totally initialize `Unboxer` in your own code. The initializer is part of the public API 👍.

As for arrays, you can use the custom unboxing API for this:

```swift
let urls: [URL] = try Unboxer.performCustomUnboxing(array: jsonArray) { unboxer in
     return try unboxer.unbox(key: "important_url")
}
```

This will be a lot cleaner in 3.0 btw:

```swift
let urls: [URL] = try jsonArray.unboxed {
    return try unboxer.unbox(at: "important_url")
}
```

Happy you like Unbox 🎉

**Comment by christianselig** [comment]
@JohnSundell Awesome, thank you, I was just curious because I didn't see anything in particular in the README, but that makes sense.

Awesome on the array front, cheers! 👍

**Comment by JohnSundell** [comment]
@christianselig Yeah the README is long overdue for a rehaul. It's basically been the same since Unbox 1.0, over 2 years ago 😅 Will do that as part of 3.0.

**Comment by nonec** [comment]
I almost thought I found what I'm looking for with this issue. But I've an additional question ;-) 
How do you unbox such JSON Array if there's not a key? Just like the vimeo JSON up there. How would it work if I want to unbox that as [VimeoObject]?
