### ISSUE TITLE
Unbox a JSON with dynamic nested objects

### ISSUE THREAD

**Issue by grundmanise** [JohnSundell/Unbox#179]
First of all thank you for such a great library!

I have a question regarding a JSON with dynamic nested objects.

JSON:

```
      "type": {
        "id": 14,
        "caption": "Liquor stores",
        "code": "",
        "parent": {
          "id": 1,
          "caption": "Food and Drink",
          "code": "food_and_drink",
          "parent": ""
        }
      },
```

Where each `"parent"` can also have a parent. Parents are dynamic so it can easily be 3-5 parents deep.

How can one  `unbox` this JSON?

Also I don't know how to correctly 'unloop' my model..

```
struct Foo {
    let type: Type
}

struct Type {
  let id: Int
  let code: String
  let caption: String
  let parent: Type?   // <-- infinite loop here...
}
```

Would be very thankful if anyone can help me.

**Comment by JohnSundell** [comment]
@grundmanise Happy you like Unbox 🎉 

If you have recursive references, they need to be reference types (classes). Instead of using a struct for `Type`, you need to use a class. Then, make `Type` conform to `Unboxable` and you should be good to go.

**Comment by grundmanise** [comment]
When I use it like this:

```
struct Foo {
    let type: Type
}

extension Foo {
   init(unboxer: Unboxer) throws {
      self.type = try unboxer.unbox(key: "type")
   }
}

final class Type: Unboxable {
    var id: Int
    var code: Int?
    var caption: String
    var parent: PlaceType?
    
    init(unboxer: Unboxer) throws {
        self.id = try unboxer.unbox(key: "id")
        self.code = unboxer.unbox(key: "code")
        self.caption = try unboxer.unbox(key: "caption")
        self.parent = unboxer.unbox(key: "parent")
    }
}

let foo: [Foo] = try unbox(dictionary: JSON as! UnboxableDictionary)
```

with the JSON:

```
      "type": {
        "id": 14,
        "caption": "Liquor stores",
        "code": "",
        "parent": {
          "id": 1,
          "caption": "Food and Drink",
          "code": "food_and_drink",
          "parent": ""
        }
      },
```

`print(foo)` prints empty `Type` object.

**Comment by JohnSundell** [comment]
@grundmanise You can't unbox a dictionary into an array. You can either unbox an array of dictionaries into an array, or start unboxing a dictionary from a given key/keyPath into an array. In this case, update your code to:

```swift
let foo: Foo = try unbox(dictionary: JSON as! UnboxableDictionary)
```

**Comment by grundmanise** [comment]
@JohnSundell oh, sorry, that's a typo. Actually it was my inattention.. because `print` does not print nested structures.. when I use `dump` everything ok. Thank you for help and directing on the right path.

**Comment by JohnSundell** [comment]
@grundmanise No problems, happy it worked out 👍
