### ISSUE TITLE
Update Object Rather Than Initialize

### ISSUE THREAD

**Issue by rcdilorenzo** [JohnSundell/Unbox#18]
@JohnSundell: First of all, I want to thank you for this library. I love it. I'm currently using this in a Mac app I'm working on and am using CoreData for persistence. Currently, I'm performing updates like below but I realize this is a sort of hack to get `Unbox` to fit my model. Is there a way to pass in an `Unbox` object to a function without having it call the `init` method. If you have any good solutions, I would love to hear.

```swift
required convenience init(unboxer: Unboxer) {
    let context = unboxer.managedObjectContext()
    self.init(entity: Task.entity(context), insertIntoManagedObjectContext: context)
    if let task: Task = Task.findByID(context, id: unboxer.unbox("id")) {
        updateProperties(task)
        context.deleteObject(task)
    }
    id = NSNumber(integer: unboxer.unbox("id"))
    // ... and the rest of the properties
}
```

**Comment by JohnSundell** [comment]
Hi @rcdilorenzo! Happy to hear that you like Unbox :)

One way to solve this is to use an intermediate data format between your JSON data and Core Data. For example, you could have a `EntityReference` model that contains an `id` (and any other data you get from JSON to be able to perform CoreData lookups for the rest of the data). That way you have decoupled Unbox from your Core Data loading code, and allows you to keep the Core Data loading code out of your model layer as well. Would that work?

**Comment by rcdilorenzo** [comment]
That's quite a bit of overhead particularly if you have many models. I've forked the repo and made a tiny change that allowed me to do exactly what I needed. The changes are at https://github.com/rcdilorenzo/Unbox/commit/f54badbfc9bcb7c5b8a536b1d13423f8f03ded88. If you are comfortable making those two things public, I'll create a pull-request. By allowing the creation directly of an `Unbox` object, it makes the library infinitely more extendable.

**Comment by JohnSundell** [comment]
Yeah that's true. The only danger I see with making `Unboxer` publically initializable is that the `failed` mechanism can't be guaranteed to work properly when used outside of Unbox. An API user might think that the same `Unboxer` instance can be used throughout the application, causing one failed unboxing processs to forever mark it as `failed`. Maybe a static API would accomplish the same thing, without exposing the initializers? Like this:

```
Unboxer.performUnboxing({
   let unboxer = $0
   var model = MyModel()
   model.string = "Hello"
   return model
})
```

What do you think @rcdilorenzo?

**Comment by rcdilorenzo** [comment]
That might work, but you'd need to pass in the `NSData` or whatever input to it.

**Comment by JohnSundell** [comment]
Yeah exactly, the `performUnboxing` method would take either an `UnboxableDictionary` or `NSData` and produce `T`.

**Comment by rcdilorenzo** [comment]
That would work. I just thought of an idea though. I ended up writing a protocol that requires an `findOrCreate` sort of method and then an `update` sort of method where the `Unboxer` object (and optionally its context) is passed it. I think that might be actually preferable to your suggestion but may not be as flexible in its use cases. What do you think?

**Comment by JohnSundell** [comment]
Yeah, I think it might be a bit too specific for the scope of Unbox, since the library shouldn't really be aware of the context that it is being used in. Plus, as you say, the static method approach gives us the most flexibility, which will probably unblock other usecases in the future :) I can probably find some time to add the static method API tomorrow.

**Comment by JohnSundell** [comment]
@rcdilorenzo After some delay the PR introducing the new custom unboxing API is now ready! Please have a look :) https://github.com/JohnSundell/Unbox/pull/22
