### ISSUE TITLE
enhancement - add instructions to ignore certain exceptions 

### ISSUE THREAD

**Issue by wwe-johndpope** [JohnSundell/Unbox#183]
add instructions to ignore certain exceptions
http://stackoverflow.com/questions/14370632/ignore-certain-exceptions-when-using-xcodes-all-exceptions-breakpoint

trying to step through app is painful. 
<img width="1322" alt="screen shot 2017-05-17 at 1 19 59 pm" src="https://cloud.githubusercontent.com/assets/26149651/26167055/b1e1aa5e-3b03-11e7-94c0-dafeb663c210.png">

**Comment by clayellis** [comment]
@wwe-johndpope I'd be happy to help, but I'm afraid I don't understand exactly what your question is.

**Comment by clayellis** [comment]
@JohnSundell this one can probably be closed if @wwe-johndpope doesn't have any other questions.

**Comment by JohnSundell** [comment]
Yeah this seems unrelated to Unbox, closing.

**Comment by wwe-johndpope** [comment]
problem with  using unbox is that it throws 1000 > of exceptions by it's nature. 
Need a way to ignore them. It's a configuration in xcode. 
eg. this is a related way to ignore errors using core data. 

<img width="741" alt="screen shot 2017-06-05 at 11 01 37 am" src="https://cloud.githubusercontent.com/assets/26149651/26789473/64639e88-49de-11e7-8ad3-6588b4382bce.png">

https://stackoverflow.com/questions/14370632/ignore-certain-exceptions-when-using-xcodes-all-exceptions-breakpoint

need to document the way to do this 

1) Add a Symbolic Breakpoint on objc_exception_throw
2) Set a Condition on the Breakpoint to (BOOL)(! (BOOL)[[(NSException *)$x0 className] hasPrefix:@"_NSCoreData"])
