### ISSUE TITLE
parsing coredata objects

### ISSUE THREAD

**Issue by SuvarnaRatna-DevRabbit** [JohnSundell/Unbox#196]
Can we use Unbox with CoreData objects. 

If so can you please help me.

**Comment by JohnSundell** [comment]
@SuvarnaRatna-DevRabbit Sure, you can extend your `NSManagedObject`s to support Unbox, just like any other object, like this:

```
extension MyObject: Unboxable {
    init(unboxer: Unboxer) throws {
        ...
    }
}
```
