### ISSUE TITLE
When to support for Support for Swift 4?

### ISSUE THREAD

**Issue by Wangxiaotao** [JohnSundell/Unbox#206]

**Comment by JohnSundell** [comment]
Now https://github.com/JohnSundell/Unbox/pull/207 🙂

**Comment by JohnSundell** [comment]
But even without that PR Unbox works with Swift 4, since it can run unmodified in Swift 3.2 compatibility mode.

**Comment by Wangxiaotao** [comment]
all right， thanks

**Comment by snap9** [comment]
Swift now has built-in JSON stuff doesn't it? Are there any added benefits to Unbox?

**Comment by JohnSundell** [comment]
@snap9 please see this issue: https://github.com/JohnSundell/Unbox/issues/191, for my answer to that question.
