### ISSUE TITLE
Ambiguous use of `unbox(key:isKeyPath:)` on Xcode 9 GM for unboxing [String]

### ISSUE THREAD

**Issue by akwilliamson** [JohnSundell/Unbox#208]
Simplified for brevity:

```
struct Foo {
    let bars: [String]
}

extension Foo: Unboxable {
    init(unboxer: Unboxer) {
        self.bars = unboxer.unbox(key: "bars")
    }
}
```
This worked fine in Xcode 8.3, but in Xcode 9 GM, it throws the error

> Ambiguous use of `unbox(key:isPath)`

Any idea why? For what it's worth, I can unbox arrays of objects that conform to `Unboxable` just fine without any errors thrown, but unboxing this array of strings throws a compile time error.

**Comment by JohnSundell** [comment]
Hey @akwilliamson 👋 Can you try this on the latest `master`? I can't seem to reproduce it.

**Comment by akwilliamson** [comment]
Huh, a project clean and it went away. Sometimes...*sigh*. Disregard!

**Comment by JohnSundell** [comment]
Haha yeah, sometimes Xcode works in mysterious ways 😅

**Comment by hawkwood** [comment]
I am having this issue too.  I'm using Xcode 9.0.1, Unbox 1.9.0, I've cleaned, deleted derived data, even deleted my repo and re-pulled, but the error still shows.  Interestingly, if I change the class from `String` to `Int` it compiles fine, but I need strings. If I comment out:
public func unbox<T: Collection>(key: String, isKeyPath: Bool = true) -> [T] {...}
The error comes and goes, but the compile does complete.
