### ISSUE TITLE
How does unbox parse a heterogeneous array with inherited classes? 

### ISSUE THREAD

**Issue by pavankataria** [JohnSundell/Unbox#222]
Hi John, I was reading an article on deserialisation in swift and wondered how Unbox would achieve the scenario described in the article: 

https://medium.com/tsengineering/swift-4-0-codable-decoding-subclasses-inherited-classes-heterogeneous-arrays-ee3e180eb556

In short, drink is a base class, and beer, water, and orangeJuice are subclasses with their own required deserialisable properties. And here's the array to parse:
```{
    "drinks": [
        {
            "type": "water",
            "description": "All natural"
        },
        {
            "type": "orange_juice",
            "description": "Best drank with breakfast"
        },
        {
            "type": "beer",
            "description": "An alcoholic beverage, best drunk on fridays after work",
            "alcohol_content": "5%"
        }
    ]
}```

I'd be interested to know how Unbox would deal with this
Thanks John

**Comment by clayellis** [comment]
@pavankataria I've referred to that article a couple times myself when using `Codable`. Here's how I would approach the same problem using `Unbox`:

```swift
import Foundation
import Unbox

let json = """
{
    "drinks": [
        {
            "type": "water",
            "description": "All natural"
        },
        {
            "type": "orange_juice",
            "description": "Best drank with breakfast"
        },
        {
            "type": "beer",
            "description": "An alcoholic beverage, best drunk on fridays after work",
            "alcohol_content": "5%"
        }
    ]
}
"""

class Drink: Unboxable {
    let type: String
    let description: String

    required init(unboxer: Unboxer) throws {
        type = try unboxer.unbox(key: "type")
        description = try unboxer.unbox(key: "description")
    }
}

class Beer: Drink {
    let alcoholContent: String

    required init(unboxer: Unboxer) throws {
        alcoholContent = try unboxer.unbox(key: "alcohol_content")
        try super.init(unboxer: unboxer)
    }
}

struct DrinkCollection: Unboxable {
    let drinks: [Drink]

    private struct DrinkContainer: Unboxable {
        let drink: Drink

        private enum DrinkType: String, UnboxableEnum {
            case water
            case orangeJuice = "orange_juice"
            case beer
        }

        init(unboxer: Unboxer) throws {
            let type: DrinkType = try unboxer.unbox(key: "type")
            switch type {
            case .water, .orangeJuice:
                drink = try Drink(unboxer: unboxer)
            case .beer:
                drink = try Beer(unboxer: unboxer)
            }
        }
    }

    init(unboxer: Unboxer) throws {
        let drinkContainers: [DrinkContainer] = try unboxer.unbox(key: "drinks")
        drinks = drinkContainers.map { $0.drink }
    }
}

let data = json.data(using: .utf8)!

do {
    let drinkCollection: DrinkCollection = try unbox(data: data)
    let drinks = drinkCollection.drinks
    print(drinks) // [Drink, Drink, Beer]
    print((drinks[2] as! Beer).alcoholContent) // 5%
} catch {
    print("Error: \(error)")
}
```

The main idea here is to use an intermediate object `DrinkContainer` which we can use as a homogenous container (it can contain any type of `Drink`). As we unbox those containers, we determine what type of `Drink` it contains using a `DrinkType` `UnboxableEnum`, and then `switch`ing on that type we unbox the correct type of `Drink`.

Once we've unboxed the `DrinkContainer`s in `DrinkCollection.init(unboxer:)`, we simply pull the drink out of each container using `map` and assign that array to `drinks`.

Hope that is useful to you! Feel free to ask any questions you might have!

If you don't have any more questions, would you mind closing the issue?

**Comment by pavankataria** [comment]
Hey @clayellis. This was more of a what if scenario as I have required this feature before and solved this in other ways before I started using Unbox. Using factory classes and so on. I'll bookmark this for when I need it. Thank you.
