### ISSUE TITLE
Accessing values from an object in an array

### ISSUE THREAD

**Issue by patrickbdev** [JohnSundell/Unbox#24]
Hi John, fantastic library!
I was curious if it was possible to do something similar to what ObjectMapper does:
```swift
distance <- map["distances.0.value"]
```

This is getting **value** from the first object in the JSON **distances** array.
My current workaround is to either create a UnboxableByTransform transformer or in my init create a local array and traverse it.

**Comment by JohnSundell** [comment]
Hi Patrick,

Happy to hear that you like Unbox :)

The way I've handled similar situations in the past is something like this:
```
struct Model: Unboxable {
    var value: String
    
    init(unboxer: Unboxer) {
        let values: [String] = unboxer.unbox("values")
        
        if let value = values.first {
            self.value = value
        } else {
            self.value = ""
            unboxer.failForInvalidValue(values, forKey: "values")
        }
    }
}
```

But it would actually be really nice if Unbox could take care of that automatically. I'll add an API for that!

**Comment by JohnSundell** [comment]
Done! :) https://github.com/JohnSundell/Unbox/commit/9be5ad33232825141eed8b71f158330891b90044

**Comment by patrickbdev** [comment]
Fantastic, thanks so much!

**Comment by JohnSundell** [comment]
@patrickbdev No worries, let me know if you need APIs for any of the other types, like nested `Unboxable`s or `UnboxableByTransform`. Those can easily be added :)
