### ISSUE TITLE
Issue with UnboxPathNode using static instead of dynamic framework

### ISSUE THREAD

**Issue by andresbrun** [JohnSundell/Unbox#246]
Hi John,

first I have to thank you for your library, I really like it :)

Recently we migrated to Swift 5 and start using the version 4.0.0 of your library and we have started to experimenting issues mainly with keyPaths.

![image](https://user-images.githubusercontent.com/2039612/55681621-9f701f00-5928-11e9-9d04-9c88fc8c3502.png)

This happens with the following JSON:

![image](https://user-images.githubusercontent.com/2039612/55681633-bf9fde00-5928-11e9-8a00-0607f04ab335.png)

It ends up raising an exception because it is not capable of unbox
```swift
let marketingOptOut: Bool = try unboxer.unbox(keyPath: "opt_outs.marketing")
```

Could you provide us any help? 

Thanks so much in advantage!

## Environment
- Compiled statically with Carthage (0.32.0)
- Xcode 10.2
- Swift 5.0

**Comment by JohnSundell** [comment]
Hey @andresbrun! Glad to hear you like Unbox. Could you please submit a test that reproduces the above issue as a PR and I'll have a look at it? 🙂

**Comment by andresbrun** [comment]
It is going to be complicated but I will try. The issue happens when I add this library statically instead of dynamically to my project. It is like the extensions that are defined in "unused" files (Dictionary+Unbox.swift) are invisible until the you touch something from that file ¯\_(ツ)_/¯.

**Comment by andresbrun** [comment]
I've found out this is a known Swift issue (https://bugs.swift.org/browse/SR-6004) so I can close this Issue. Thanks!
