### ISSUE TITLE
Hey, new to unbox

### ISSUE THREAD

**Issue by pavankataria** [JohnSundell/Unbox#27]
I'm just trying to get something together here.

I have 
```
Agent.swift
Agent+CoreDataProperties automatically managed by xcode
```
**Agent.swift** just looks like this:
```
class Agent: NSManagedObject {
//    required init(unboxer: Unboxer) {
//        
//    }

```

**Agent.CoreDataProperties.swift** looks like this.

```
extension Agent {
    @NSManaged var globalId: String?
    @NSManaged var name: String?
    @NSManaged var percentageDiscount: NSNumber?
    @NSManaged var balance: NSNumber?
    @NSManaged var note: String?
}

```

I'm trying to get the unboxer initialiser working but I'm not sure how to go about doing that since it wants me to call a desginated core data initialiser?
I want to parse some json and get rolling. 
Could you perhaps explain how to use your package with my simple common example please?

Thank yo

**Comment by pavankataria** [comment]
@JohnSundell just a quick ping. Hope you're having a good weekend.

**Comment by JohnSundell** [comment]
Hey @pavankataria, sorry for the late reply.

When using Unbox together with Core Data, it usually is easier to use the Custom Unboxing API introduced in Unbox 1.3. Basically it enables you to get more fine-grained control over the Unboxing process (by not using a required `init`), so that you can perform both JSON decoding any Core Data operations in one go.

The reasonining behind the Custom Unboxing API and how to use it with Core Data was discussed here: https://github.com/JohnSundell/Unbox/issues/18

Please check the `README` for more information about the Custom Unboxing API.

**Comment by pavankataria** [comment]
Hey, so I have read that read me, I just didn't know how that would fit in with my current two files that I have especially with the load dependency stuff.

**Comment by JohnSundell** [comment]
No worries :) Did my reply clear things up, or do you need any further assistance?

**Comment by pavankataria** [comment]
>  is it possible for you to show how this would tie in together with my two files?

**Comment by JohnSundell** [comment]
Sure, here is some example code:

```
// Load your data
let data: NSData = ...

let agent: Agent = try Unboxer.performCustomUnboxingWithData(data, closure: {
    let unboxer = $0
    let agent = Agent()
    agent.globalId = unboxer.unbox("globalId")
    agent.name = unboxer.unbox("name")
    
    // Etc for the rest of your properties

    return agent
})
```

In what file you put this code is completely up to you. Perhaps create a `AgentLoader` or put the code inline where you're loading your data, or add an extension on `Agent`.

The Custom Unboxing API only supports `Dictionaries` right now, so with the current API you'd have to iterate over the dictionaries, unboxing each one, but we could always add a Custom Unboxing API that has support for `Arrays` (the main `Unbox()` API does)

**Comment by drallgood** [comment]
hmm.. This is not really clear to me.
Neither is the README.

Given that I have a Core Data object like @pavankataria how would I proceed to have Unbox integrated?

**Comment by JohnSundell** [comment]
@drallgood Does the example code I provided above not work for you? (note that it was written in Swift 2). If you tell me exactly what is unclear I can try to explain and improve the README.

**Comment by drallgood** [comment]
@JohnSundell 
The code would probably work, IF i knew where to put it. ;)
I think a full example would be great. Data model and all
