### ISSUE TITLE
Support for '.' in JSON key name

### ISSUE THREAD

**Issue by sandalsoft** [JohnSundell/Unbox#29]
I'm receiving JSON from a source that has periods(.) in the key names (see below)

Attempting to use the key name returns nil.    
`self.sourcePort = unboxer.unbox("_source.src.port")`

A period in key names is valid JSON.  Looking into the code, I can see the key is split into components on the . character for key path support, so I'm not even sure what I would do to 'fix' the issue.  I played around with surrounding the key name with " " or [], but they didn't feel right.  Am open to working on a PR for this or any workarounds.

     "_id": "5951785333"
     "_source": {
        "emailsender": "",
        "app": "smtp",
        "src.countrycode": "VN",
        "dst.port": 25,
        "src.ip": "113.175.119.199",
        "device.industry": "High Tech",
        "sha256": "5248d5aa00d0b5d04050732d4d519cccd84c4d4c2e86c0ed4aed7807e185f0a1",
        "src.port": 40583,
        "fileurl": "unknown",
        "emailsbjcharset": "",
        "tstamp": "2015-04-05T20:52:44",
        "device.serial": "0008C100299",
        "device.country": "Hong Kong",
        "device.countrycode": "HK",
        "src.country": "Viet Nam",
        "emailsubject": "Returned mail: Data format error",
        "device.hostname": "PA-5060",
        "dst.country": "Hong Kong",
        "dst.countrycode": "HK",
        "dst.ip": "158.132.50.91",
        "filename": "wtctl.zip",
        "user_id": "unknown",
        "emailrecipient": "hsfwong@inet.polyu.edu.hk",
        "vsys": 1
     }

**Comment by mr-v** [comment]
Oops, looks like I'm the one to blame for that (#4). Was thinking for some time about changing it to more explicit API, e.g. `unboxer.unboxKeyPath(["_source", "app"]`). Didn't find time for making that change/pull request unfortunately.
The way it works now was convenient at the time, but I admit it's a little hacky.

**Comment by mr-v** [comment]
Looks like adding `unboxKeyPath` would require adding implementations mirroring each `unbox` overload. There are a lot of those, so need to make sure if the following approach is right: extract deepest dictionary and key, call right overload, make sure it works with test. Here's sample implementation for UnboxableRawType: https://github.com/mr-v/Unbox/commit/815b4046278ab1f3d347f377e096873873153baf 

 @JohnSundell Is that the way to do it or perhaps I've missed something?

**Comment by JohnSundell** [comment]
@mr-v Yeah I don't think adding additional overloads for keypaths is a good idea. It'll be a lot of extra code that'll easy get out of sync with the normal non-keypath API. One way to solve this would be to add a `isKeyPath` bool argument to each `unbox()` overload (with a default `false` value). That way you have to explicitly say that you want Unbox to treat your string as a keypath, so that issues like this one can be avoided.

**Comment by mr-v** [comment]
> Yeah I don't think adding additional overloads for keypaths is a good idea.

Agree, it could be hard to maintain and file would grow a lot.

What about this implementation? ([commit](https://github.com/mr-v/Unbox/commit/75ff84cfe2e590f0c6547bf901716273fd50f48d))
```swift
public func unbox<T: UnboxableRawType>(key: String, isKeyPath: Bool = false) -> T {
        let (unboxer, finalKey) = !isKeyPath ? (self, key) : unboxerAndKeyForKeyPath(key)
        return UnboxValueResolver<T>(unboxer).resolveRequiredValueForKey(finalKey, fallbackValue: T.unboxFallbackValue())
}
```

Handling `isKeyPath` in each overload would be limited to adding

```swift
let (unboxer, finalKey) = !isKeyPath ? (self, key) : unboxerAndKeyForKeyPath(key)
```

and  using `unboxer` and `finalKey` with `UnboxValueResolver`.

**Comment by JohnSundell** [comment]
@mr-v Solved it with a combination of your suggestion and moving the actual check to `UnboxValueResolver`. Thanks for your input! :)

@sandalsoft The issue is fixed, will prepare a new release.

**Comment by JohnSundell** [comment]
@sandalsoft New release published, both here on GitHub and on CocoaPods. Update to `1.3.1` to get the fix.

**Comment by sandalsoft** [comment]
Daaaaamn, you guys rock!!  Thanks a bunch, I'll test this out tomorrow.

**Comment by JohnSundell** [comment]
@sandalsoft :rocket:

**Comment by sandalsoft** [comment]
I just tested this and it's not working for child keypaths that have a . in the key name.

json:



     "_id": "5951785333"
     "_source": {
        "emailsender": "",
        "app": "smtp",
        "src.countrycode": "VN",
        "dst.port": 25,
     }


parsingClass.swift
```
let sampleDict = json 
        do {
          let sample: Sample = try UnboxOrThrow(sampleDict)
          arrayOfSamples.append(sample)
        } catch let unboxingError{
          print("Error:  \(unboxingError)")
        }
      }
```

Sample.swift

```
  init(unboxer: Unboxer) {
    self.id = unboxer.unbox("_id) // works
    self.app = unboxer.unbox("_source.app") // works
    self.sourceCountryCode = unboxer.unbox("_source.src.countrycode",  isKeyPath: true) // nil
    self.destinationPort = unboxer.unbox("_source_dst.port") // nil
...
```


`self.sourcePort = unboxer.unbox("_source.src.countrycode", isKeyPath: true)` returns nil.  Which makes sense based on the new code.  As a workaround I pulled out the `_source` dictionary and used that as the constructor parameter and the `_id` as the context.



```

let sourceDict = sampleDict["_source"] as! [String: AnyObject]
        do {
          let sample: Sample = try UnboxOrThrow(sourceDict, context: sampleDict["_id"] as! String )
          arrayOfSamples.append(sample)
        } catch let unboxingError{
          print("Error:  \(unboxingError)")
        }
      }


```


This works for me.  Thanks for the help guys.

**Comment by JohnSundell** [comment]
Yeah, you won't be able to combine a keypath with a key with a dot in it. I think this is a reasonable tradeof as the keypath API is a convenience in the first place (the alterantive would be to introduce all the overloads that we talked about earlier and do an array-based API for keypaths, which will be too heavy). 

The way I usually solve nested dictionaries (regardless of if they have a dot in the key) is to use nested `structs`. So that each dictionary maps to a `struct`. This generates a bit more code, but is easier to reason about (and test!) IMO. Like, in your case, I'd let `Source` be its own `struct´, nested within your root object. But it's up to you what approach to take :)
