### ISSUE TITLE
Enum fallback not working (Unbox 1.3)

### ISSUE THREAD

**Issue by timlentonBCGDV** [JohnSundell/Unbox#32]
If I have an optional enum property then the fallback method is not called and the optional is nil, and if I have a non-optional enum property then the fallback method is called however Unbox fails.

enum Bar: String, UnboxableEnum {
  case Bar1
  case Bar2
  public static func unboxFallbackValue() -> Bar {
    return .Bar1
  }
}

class Foo: Unboxable {
  var bar: Bar
  required init(unboxer: Unboxer) {
    self.bar = unboxer.unbox("bar")
  }
}

Unboxing throws for the code above using this JSON:

{"bar" : "THIS IS NOT IN THE LIST"}

If I change the Foo class to make bar optional (var bar: Bar?) then unboxFallbackValue is not called. The same happens if the property is missing from the JSON i.e. {} in the example above. 

Am I missing something? Thanks

**Comment by timlentonBCGDV** [comment]
(Basically I think the fail state should be cleared if the fallback is used)

**Comment by timlentonBCGDV** [comment]
There is another case also - where you have a non-optional enum property and you want to fail the Unbox if a matching enum value is not in the JSON. Could this be achieved by making the fallback method in the UnboxableEnum protocol optional instead of required?

**Comment by JohnSundell** [comment]
The `unboxFallbackValue()` method is only called by Unbox if the decoding of a required value failed, and it needs a dummy value to assign to the property before failing the process. From the documentation:
```
/// The value to use for required properties if unboxing failed. Typically a dummy value.
static func unboxFallbackValue() -> Self
```

To assign a default value in case one can't be found, you want Swift to treat your value as an optional, which will call the correct `unbox()` overload on `Unboxer`, like this:

```
Model: Unboxable {
    let name: String

    init(unboxer: Unboxer) {
        self.name = unboxer.unbox("name") ?? "Default name"
    }
}
```

You can also perform your own sanity-checking of a value, and if it doesn't pass such a check, you can call `failForKey()` or `failForInvalidValue(forKey:)` on the current `Unboxer`.

**Comment by timlentonBCGDV** [comment]
Thanks for getting back John, I've got it now - the unboxFallBackValue is purely there to facilitate the fail on an non-optional enum.

All this actually came up while I was trying to abstract the unboxing code from the models themselves. But if I put the unboxFallbackValue() method in an extension on the enum it causes a segmentation fault on build unless the extension is in the same swift file as the enum itself. 

I'm also getting a segmentation fault: 11 when I try to unbox a generic that conforms to Unboxable instead of the class itself.

This is with Unbox 1.2.4 and Xcode 7.2.1 - have you seen anything like this? I will raise a new issue for it with more detail if you think it's worthwhile.

**Comment by timlentonBCGDV** [comment]
Avoided the segmentation fault issues by giving up on the idea of abstracting the unboxing code from my models.

**Comment by JohnSundell** [comment]
@timlentonBCGDV Hi again, sorry for the late reply.

You're encountering the segmentation fault because Swift cannot resolve an implementation to call if you're using protocol types. Check out this discussion for more info: https://github.com/JohnSundell/Unbox/issues/17.

If you want to keep your unboxing code out of your models, then the Custom Unboxing API (introduced in Unbox 1.3) is the way to go. Check the `README` for more information on that.

**Comment by timlentonBCGDV** [comment]
Thanks again John, I'll check out the Custom Unboxing API (I got my version numbers mixed up there apologies, I already was on 1.3).
