### ISSUE TITLE
Unboxing nested Arrays

### ISSUE THREAD

**Issue by knutnyg** [JohnSundell/Unbox#34]
I am trying to get Unbox to work with my app, but I'm stuck at unboxing the JSON from an endpoint I'm consuming.

The response is of type:
```
{  
   "data":[  
      [  
         123.0,
         123.1
      ],
      [  
         456.0,
         789.0
      ]
   ]
}
```
I can't for the life of me get unbox to work with a nested array of type [[Double]]. Is this not supported? Any help is greatly appreciated :)

**Comment by JohnSundell** [comment]
Hi @knutnyg! You're right - this is not supported yet - but it definetly should be! I think the fix would be to finally promote `Array` to an `UnboxableRawType`, this however, will require some more changes to make sure supporting nested arrays of `Unboxable` types are still handled correctly. I'll see if I can work on a fix tomorrow :)

**Comment by knutnyg** [comment]
Cheers! :+1:

**Comment by JohnSundell** [comment]
Sorry this has taken so long @knutnyg! A lot of other things have come up in between, haven't forgotten about this though! Hope to be able to prepare a fix asap :)

**Comment by pavankataria** [comment]
How's it coming along? :D

**Comment by krystiansliwa** [comment]
Do you have any fix for that?

**Comment by JohnSundell** [comment]
@knutnyg @pavankataria @krystiansliwa: Finally got time to work on this 🎉 Sorry for the delay, but this patch fixes the problem: https://github.com/JohnSundell/Unbox/issues/51
