### ISSUE TITLE
Module file's minimum deployment target is ios9.2 v9.2

### ISSUE THREAD

**Issue by Shun-Nakahara** [JohnSundell/Unbox#37]
Module file's minimum deployment target is ios9.2 v9.2: /Users/*/Build/Products/Debug-iphonesimulator/Unbox.framework/Modules/Unbox.swiftmodule/i386.swiftmodule

thank you,

**Comment by JohnSundell** [comment]
This should fix it: https://github.com/JohnSundell/Unbox/commit/388571bcdc8fdbded865b3010a2f501cfa32d979 Let me know if you experience any other issues.
