### ISSUE TITLE
Unbox with fallback value?

### ISSUE THREAD

**Issue by basememara** [JohnSundell/Unbox#39]
Great library, thanks for sharing! Much appreciated for creating a slim and un-invasive object mapper, unlike almost all others out there :)

I'm trying to unbox a complex JSON endpoint into an array of custom types like this:
`let items: [Post] = Unbox(data)`

In my `init`, I set one of my properties like this:
`thumbnailHeight = unboxer.unbox("featured_image.attachment_meta.sizes.thumbnail.height", isKeyPath: true)`

But my `[Post]` array is empty because it fails on one of the items in the endpoint with this error:
`Missing key (featured_image.attachment_meta.sizes.thumbnail.height)`

So I was hoping to set a fallbackValue for this property so instead of failing for the whole collection, it would use a default value for this iteration/property and move on to the rest. Is something like this possible?:
`thumbnailHeight = unboxer.unbox("featured_image.attachment_meta.sizes.thumbnail.height", isKeyPath: true, fallbackValue: 0)`

**Comment by basememara** [comment]
Thanks for getting back to me. I realized there was something else that was tripping me up, not default values. Regarding the default values though, what I wanted to keep my properties as non-optional? Since `??` couldn't be used in that case, the `fallbackValue` can fill it in. #40 is supposed to extend that option.

What was really tripping me up was I was using `Unbox` not `UnboxOrThrow`, so it was silently swallowing items or entire collections that had invalid data. So even if there was one invalid object in an array of objects, the whole collection would be returned empty. What #41 does is add `UnboxOrSkip` so it can just skip the invalid property of an object or object in a collection. What do you think?

**Comment by basememara** [comment]
Ah I see what you're saying, true I can simply unbox it temporarily then assign it to the non-optional property later - doh! You can disregard #40, was good to dig through the library anyway :)

**Comment by JohnSundell** [comment]
Cool :) I'll close this issue and https://github.com/JohnSundell/Unbox/pull/40 for now, and we can continue the discussion in #41 :)
