### ISSUE TITLE
Framework for Carthage support

### ISSUE THREAD

**Issue by bartcone** [JohnSundell/Unbox#5]
Any plans to make this an actual framework so people can use Carthage?

**Comment by JohnSundell** [comment]
Sure, we can do it! :+1: I can add a thin Xcode wrapper project that builds a framework, so that Cathage can be supported.

**Comment by bartcone** [comment]
Cool, thanks.

**Comment by JohnSundell** [comment]
Alright, Carthage should now be supported. Added instructions how to use Unbox with Carthage to the Readme too :)
