### ISSUE TITLE
Unbox crashing in iOS7 with BAD_ACCESS

### ISSUE THREAD

**Issue by acecilia** [JohnSundell/Unbox#52]
In any line initiating an object of type "UnboxValueResolver" unbox is experiencing a runtime crash with BAD_ADDRESS due to a bug in the compiler reported [here](https://bugs.swift.org/browse/SR-1201) and [here](https://bugs.swift.org/browse/SR-815). Seems happening just in iOS7 (I tested it in a real iPhone4 with iOS 7)

Not an issue of Unbox, but is good to have it in mind (and not waste 2 hours trying to find the reason of the crash ;P)

**Comment by JohnSundell** [comment]
Unbox doesn't support iOS7, it's iOS8+. Should probably clearify that in the README though, will fix :)

**Comment by JohnSundell** [comment]
README updated :)
