### ISSUE TITLE
Parse String to Int

### ISSUE THREAD

**Issue by hunaid-hassan-confiz** [JohnSundell/Unbox#55]
I have a `price` property in my JSON model which I receive as String but I want to parse it to Int upon unboxing so I dont have to typecast it everywhere I use it. Is there a documented way of doing it?

**Comment by hunaid-hassan-confiz** [comment]
I ended up doing this
`price = Int(unboxer.unbox("price") as String)!`

**Comment by JohnSundell** [comment]
Hi @hunaid-hassan-confiz! Thanks for highlighting this issue, we should definety add a 1-liner so that you can just do `unboxer.unbox("price")`! 👍

**Comment by JohnSundell** [comment]
This commit implements what you're looking for: https://github.com/JohnSundell/Unbox/commit/2fa63dd92701b751f5c9fdbee736c1665cfec0f8

Now you can just do:

```
self.price = unboxer.unbox("price")
```

Which will convert a string for that key into a number of the type that you're expecting.
Will make a new release soon that includes the fix :)

**Comment by hunaid-hassan-confiz** [comment]
Great job, sir :)

**Comment by hunaid-hassan-confiz** [comment]
Functionality works as expected but the unit tests are not testing the functionality properly I guess.
Have a look at the note i posted in the mentioned commit.

**Comment by JohnSundell** [comment]
Thanks again for that comment - totally missed that! 👍 This commit corrects the test: https://github.com/JohnSundell/Unbox/commit/975784378c724c7bb5043a1fca0f80f5f7c96399
