### ISSUE TITLE
Unbox not parser a simple String

### ISSUE THREAD

**Issue by douglasalexandre** [JohnSundell/Unbox#58]
I had a problem with `Unbox` if I have a 'response` JSON` with a simple `string` instead of an `array` or an `object` in `swift 2.2`
```
Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}
```
`Class Model`
```
struct TokenModel: Unboxable {
    let id :String
    let name :String
    let token :String
    let urlAccess :String
    
    init(unboxer: Unboxer) {
        id = unboxer.unbox("id")
        name = unboxer.unbox("name")
        token = unboxer.unbox("token")
        urlAccess = unboxer.unbox("urlAccess")
    }
}
```
`JSON Response API`
` null({"id":7,"name":"uniplam","token":"uniplam","urlAccess":"https://X.XX.XXX.0:8082/uniplam/"})`

The Object Parse will try to parse a JSON to a model using the Unbox framework

```
public class ObjectParser<T: Unboxable>: NSObject {
    let jsonData :NSData
    required public init(jsonData data:NSData) {
        jsonData = data
        super.init()
    }
  
    public func parsedResponse() -> (response :T?, error :ErrorType?) {
        do {
            let object :T = try UnboxOrThrow(jsonData)
            return (object, error: nil)
        }
        catch (let error) {
            return (nil, error: error)
        }
    }
```

I believe that `Unbox` don't prepare for parser a simple `String`, or not?

**Comment by JohnSundell** [comment]
Hi @douglasalexandre,

If the string that makes up your `NSData` that you pass when initializing your `ObjectParser` starts with `null(` (as in the example), then it's not valid JSON. Valid JSON must have either an Array or Dictionary as its root object - and it looks like the server you're getting the data from is using JSON-P to wrap the returned JSON in a Javascript function call (that in this instance is `null`).

I'd recommend either looking into if you can get a standard JSON response from your server, or manually stripping out the `null(` at the beginning and `)` at the end.

**Comment by douglasalexandre** [comment]
Hi, @JohnSundell 
Thanks for the answer. I checked the `JSON` and it's wrong!
This is correct `Json`
``` {
  "id": 7,
  "name": "Uniplam",
  "token": "uniplam",
  "urlAccess": "https://xx.xx.xx.x:8082/uniplam/"
}
```
But anyway, the error still occurs.

**Comment by bre7** [comment]
First time using Unbox (already loving it)...It'd seem that you defined the model incorrectly. 

`let id :String` but the server returned an Int. So either the response is wrong or id's type is.

**Comment by douglasalexandre** [comment]
ok, @JohnSundell I will try. Thanks for the answer! :)

**Comment by JohnSundell** [comment]
@douglasalexandre Yeah, what @bre7 says is right - if you're expecting an `Int` value then your property should be an `Int` as well, optionally you could also do:
```swift
self.id = String(unboxer.unbox("id"))
```

**Comment by douglasalexandre** [comment]
@JohnSundell @bre7 Ok. Thanks for help me. Really the server is returning a `JSONP`, so, it isn't valid `JSON`. I modify my model like you spoke, with right types. We will modify our server :)
