### ISSUE TITLE
Problem with struct

### ISSUE THREAD

**Issue by sembsa** [JohnSundell/Unbox#6]
If create new struct, Xcode write me error: Type 'Weather' does not conform to protocol 'Unboxable' I don't know this :(

**Comment by JohnSundell** [comment]
Can you show me the declaration for `Weather `?

**Comment by sembsa** [comment]
`struct Weater: Unboxable {}`

**Comment by JohnSundell** [comment]
@sembsa You need to implement `init(unboxer:)` in order to conform to `Unboxable`. It's within this method you will perform the actual unboxing. Like this:

```
struct Weather: Unboxable {
     var isRaining: Bool

     init(unboxer: Unboxer) {
        self.isRaining = unboxer.unbox("isRaining")
     }
}
```

See the `README` for more thorough examples :)

**Comment by sembsa** [comment]
thanks :) It is my error, sorry. :+1:

**Comment by JohnSundell** [comment]
@sembsa No worries :)
