### ISSUE TITLE
Would you guys be willing to maintain a Swift 3 branch?

### ISSUE THREAD

**Issue by Evertt** [JohnSundell/Unbox#62]
I implemented Unbox in a Swift 3 project and I had to change quite a bit of code to be able to do that. So I would really like it if you guys would be willing to maintain such a branch. I'm willing to share with you my version so that you don't have to do that work now.

I just did a few simple find-and-replace functions for now to make it work, but maybe in the future I'm also willing to change everything so it conforms to the Swift 3 API Guidelines.

**Comment by JohnSundell** [comment]
We should totally have a Swift 3 branch, just haven't had any time to start working on it yet 😞 Feel free to submit the changes you made in a PR and I'll take a look 👍

**Comment by JohnSundell** [comment]
Working on this now 🚀

**Comment by JohnSundell** [comment]
The Swift 3 branch is here! Will still do a lot of work to make the APIs feel more at home in Swift 3, but it compiles, works and all tests are passing; https://github.com/JohnSundell/Unbox/tree/swift3
