### ISSUE TITLE
[Feature request] add subscript access

### ISSUE THREAD

**Issue by Evertt** [JohnSundell/Unbox#63]
I'm a very big fan of clean and minimal syntax, which is why I fell in love with Unbox in the first place. That is why I would love subscript access, because that can change this:

```swift
class User: Unboxable {
    let id: Int?
    let age: Int
    let active: Bool
    let name: String

    public required init(unboxer: Unboxer) {
        id     = unboxer.unbox("id")
        age    = unboxer.unbox("age")
        name   = unboxer.unbox("name")
        active = unboxer.unbox("active")
    }
}
```

Into this:

```swift
class User: Unboxable {
    let id: Int?
    let age: Int
    let active: Bool
    let name: String

    public required init(box: Unboxer) {
        id     = box["id"]
        age    = box["age"]
        name   = box["name"]
        active = box["active"]
    }
}
```

And of course for the more advanced unboxing one could still do the normal `box.unbox()`.

I like it, how about you guys?

**Comment by Evertt** [comment]
Hmm, shit, I now see that subscript access is not possible with generics... :-(

That sucks... I wonder if that is by design or just because the makers of swift wanted to focus on other stuff first.

**Comment by JohnSundell** [comment]
@Evertt Yeah, I actually started implementing Unbox using subscripting, but quickly realized that it wasn't possible :/ As you say, I think it's just a limitation and something that hasn't been implemented yet. Do you know if this has been discussed on the Swift Evolution list/repo?

**Comment by Evertt** [comment]
Yes I've seen it appear in [the swift evolution mailing list](https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20160229/011666.html), but unfortunately it seems to have been put on hold recently, because the core-team is getting a bit overwhelmed and they wouldn't be able to finish everything before swift 3 is supposed to come out.

So I think generic subscripts are probably coming in Swift 4. :-(

**Comment by JohnSundell** [comment]
Ah that's too bad :/ Understand that fully completing the generics implementation and adding support for things like subscriping is very hard though. Closing this issue for now as it's not something that we can do within the near future. Let's revisit once Swift supports subscripting for generics :)
