### ISSUE TITLE
[Feature request] return an array of failures instead of a single failure

### ISSUE THREAD

**Issue by Evertt** [JohnSundell/Unbox#64]
When I do:

```swift
let user = try Unbox(data) as User
```

If it fails, then I would like to know *everything* I did wrong, not just the first or last error that arose. In my local version I already changed the code so it gathers all the failures and then returns it as an array. Would you be open for a PR for this feature?

**Comment by JohnSundell** [comment]
Hi @Evertt, sounds like a great improvement! I agree that sometimes the debugging process can be a bit annoying, since you only get one error at a time (and if a nested error occured, you don't really know which model caused the error). Feel free to submit a PR! 👍
