### ISSUE TITLE
Enum issue

### ISSUE THREAD

**Issue by jeetendradesai786** [JohnSundell/Unbox#65]
Dear John,

I am getting exception for Enum data type

Ex. 
enum Profession : Int, UnboxableEnum {
    case None = 0
    case Developer
    case Astronaut
    
    static func unboxFallbackValue()-> Profession {
        return None
    }
}

struct Employee : Unboxable {
    let profession:Profession
    init(unboxer: Unboxer) {
      self.professionIndex = unboxer.unbox("Profession") 
///// JSON have integer value >=3 for "Profession"
    }
}

Will appreciate for assistance.

Thanks

**Comment by JohnSundell** [comment]
Hi @jeetendradesai786,

The built-in support for decoding `enums` is based on their `rawValue`. So if you are expecting something else (like `>= 3` in this case), you'd have to make your `enum` conform to `UnboxableByTransform` and write your own mapping code. Another alternative would be to unbox the underlying integer, and then handle it in your `init(unboxer:)` implementation (like I think you already started with), like this:

```
struct Employee: Unboxable {
    let profession: Profession

    init(unboxer: Unboxer) {
        let professionIndex: Int = unboxer.unbox("profession")

        switch professionIndex {
            case 3:
                self.profession = .Developer
            // And so on, for each case
            default:
                self.profession = .None // Dummy value assignment
                unboxer.failForInvalidValue(professionindex, forKey: "profession")
        }
    }
}
```

Let me know if that works for you :)

**Comment by JohnSundell** [comment]
@jeetendradesai786 Closing for now, let me know if the solution I suggested above doesn't work :)

**Comment by jeetendradesai786** [comment]
Hi John,

Thanks for the help.
Solution given works fine.


Get Outlook for iOS




On Sun, May 22, 2016 at 4:13 AM -0700, "John Sundell" <notifications@github.com> wrote:












@jeetendradesai786 Closing for now, let me know if the solution I suggested above doesn't work :)
