### ISSUE TITLE
Handler response only with 200

### ISSUE THREAD

**Issue by douglasalexandre** [JohnSundell/Unbox#67]
I am use Unbox in my project, however on request with server, the return is only `true`, a `String` . Is there any way to parser it with `Unbox`? Some trick of a Model for it?

**Comment by JohnSundell** [comment]
HI @douglasalexandre. The response that you are getting is not a JSON object, and can therefor not be handled by Unbox, `NSJSONSerialization`, or any other API that handles JSON. It's easier if you just decode the `NSData` that you downloaded into a `String` and compare it to `true`.

**Comment by douglasalexandre** [comment]
Ok, @JohnSundell. In fact, Its was just doubt! :) Thanks for answer. 👍

**Comment by JohnSundell** [comment]
No problems 👍
