### ISSUE TITLE
Unboxing CGRects from custom format

### ISSUE THREAD

**Issue by Theome** [JohnSundell/Unbox#71]
I have JSON files that encode `CGRect`s as arrays, for example `r = CGRect(x: 10, y: 10, width: 100, height: 200)` is represented as `{ "r":[10,10,100,200] }`.

Writing a wrapper for Wrap is easy:
```
extension CGRect: WrapCustomizable {
  public func wrap() -> AnyObject? {
    return [self.origin.x, self.origin.y, self.size.width, self.size.height]
  }
}
```

But now I'm trying to implement the inverse. Is it possible to add support for this format to Unbox by writing the right extensions for `CGRect`? As far as I understand, all solutions using `UnboxableRawType`, `UnboxableByTransform` or `UnboxableWithFormatter` require custom `String` parsing, which I don't want to do.

My current solution is to write an extension for Unboxer like this:
```
extension Unboxer {
  func unbox(key:String) -> CGRect {
    let a:[CGFloat] = self.unbox(key)
    if a.count == 4 {
      return CGRect(x: a[0], y: a[1], width: a[2], height: a[3])
    }
    return CGRectZero
  }
}
```

Is there a better way, using the designated customization points, that works together with the other features like getting failure info?

**Comment by JohnSundell** [comment]
Hey @Theome, you're right - using `UnboxableByTransform` is currently restricted to `UnboxRawTypes` (like `Int`, `String`, etc) - but that should definetly be fixed! Will work on a fix right now :)

**Comment by JohnSundell** [comment]
This commit fixes the problem: https://github.com/JohnSundell/Unbox/commit/94f20e380334d0ab35778521f250123c81ffca1b

Now any type can be used as a raw value for a type conforming to `UnboxableByTransform`, so you can implement an extension for `CGRect` like this:

```swift
extension CGRect: UnboxableByTransform {
    public typealias UnboxRawValueType = [CGFloat]
    
    public static func transformUnboxedValue(unboxedValue: [CGFloat]) -> CGRect? {
        if unboxedValue.count < 4 {
            return nil
        }
        
        return CGRect(
            x: unboxedValue[0],
            y: unboxedValue[1],
            width: unboxedValue[2],
            height: unboxedValue[3]
        )
    }
    
    public static func unboxFallbackValue() -> CGRect {
        return CGRect()
    }
}
```

Will make a new release with the change tonight :)

**Comment by JohnSundell** [comment]
The release has now been 🚢ed! Update Unbox to `1.6` to get the fix :)

**Comment by Theome** [comment]
Great! Thank you very much :)
