### ISSUE TITLE
How to unbox Int 64 values with unbox during deserialisation?

### ISSUE THREAD

**Issue by pavankataria** [JohnSundell/Unbox#72]
Hey, I get a `No 'unbox' candidates produce the expected contextual result type 'Int64'` error when trying to unbox a value for a Int64 data type. What is needed to get this working?

Is it a case of adding the following?

```extension Int64: UnboxableRawType {
    public static func unboxFallbackValue() -> Int64 {
        return 0
    }
}
```

I don't understand how this might make things work if that is the correct way to resolving 64 int types from a json payload.

**Comment by JohnSundell** [comment]
Hey @pavankataria, I just added support for implicit integer conversions to a number of numeric types, including `Int64`: https://github.com/JohnSundell/Unbox/commit/59bc90bba8383407d22de43ba6a33d04fddfe2b8

Will make a release including this fix during the day :)
