### ISSUE TITLE
How to parse objects that placed on custom key?

### ISSUE THREAD

**Issue by Samback** [JohnSundell/Unbox#73]
Hello I have faced with such an issue:

```
{
  "words": [
    {
      "id": 214,
      "title": "a",
      "word_category_id": 2
    },
    {
      "id": 196,
      "title": "b ",
      "word_category_id": 2
    },
    {
      "id": 176,
      "title": "c",
      "word_category_id": 2
    }
  ]
}
```

How can I parse them correctly?

Regards,
Max

**Comment by Samback** [comment]
I have done this on such a way 
```
  if let dictionary = try NSJSONSerialization.JSONObjectWithData(
                        data, options: [.AllowFragments]) as? UnboxableDictionary {
                        if let wordsDictionary = dictionary["words"] as? [UnboxableDictionary] {
                            let words: [WordSmallModel] = try Unbox(
                                wordsDictionary, context: nil, allowInvalidElements: true)
```
But I think Unbox should support this from box :) . What do you think? I can try to contribute this implementation.

**Comment by ivasic** [comment]
There's a similar question answered here: #54

**Comment by Samback** [comment]
You see I think it's not the best idea create a new struct for each one of such situations.

**Comment by JohnSundell** [comment]
Hi @Samback & @ivasic. I agree, it would be great if Unbox could handle this, since it seems to be a pretty common usecase. @Samback, feel free to contribute a solution if you have one in mind :)

**Comment by clayellis** [comment]
@JohnSundell do you think you'll have any time to implement a solution to this problem? I've run into it multiple times and it's starting to hurt. If not, it would be nice to know so I can plan accordingly.

**Comment by JohnSundell** [comment]
@clayellis Yeah, will take a look at it this week :)

**Comment by clayellis** [comment]
@JohnSundell I wonder if a possible solution could be as simple as:

    public func Unbox<T: Unboxable>(dictionary: UnboxableDictionary, at key: String, context: Any? = nil) throws -> T {
        guard let nestedDictionary = dictionary[key] as? UnboxableDictionary else { throw UnboxValueError.MissingValueForKey(key) }
        return try Unboxer(dictionary: nestedDictionary, context: context).performUnboxing()
    }

Usage:

    let json = // Some UnboxableDictionary
    let bar: Bar = try Unbox(json, at: "foo")

Bar:

    struct Bar: Unboxable {
        let bar: Int
        init(unboxer: Unboxer) {
            bar = unboxed.unbox("bar")
        }
    }

With JSON:

    {
      "foo": 
      {
        "bar": 1
      }
    }

**Comment by ivasic** [comment]
This is similar to how I've been doing it. As a bonus - it would be lovely to have an overload that accepts keypath as well. That covers a lot of cases I've ran into

**Comment by clayellis** [comment]
@ivasic Exactly—I've created a pull request for this. The solution in the pull request is slightly modified. @JohnSundell

**Comment by clayellis** [comment]
@ivasic Okay, I just added support for key paths with indices in that pull request and it passes tests. Now it's just up to @JohnSundell to accept!

**Comment by JohnSundell** [comment]
This has now been fixed by @clayellis! 🎉
