### ISSUE TITLE
isKeyPath default's value

### ISSUE THREAD

**Issue by Schaltfehler** [JohnSundell/Unbox#74]
Hi John,
Thank you for this nice project!

The other day I was wondering if there was a deeper reason for having the `isKeyPath` parameter because [here](https://github.com/JohnSundell/Unbox/blob/master/Sources/Unbox.swift#L712) you check for `isKeyPath` and `key.containsString(".")` which would make `isKeyPath` kind of unnecessary. But you probably want to stay true to the [json definition](http://www.json.org) which allows "." in their key. 

Maybe due to the use of other json mapping libs i expected that something like `name = unboxer.unbox("userInfo.name")` would work directly because I had *Key path support* in mind. Well it works but it needs an additional parameter `isKeyPath=true`.

What I try to say here is.
In real live i have hardly seen any "." in key names. I think its more common use case to use the "." as a Key Path as having it in the actual key. Thats why I want to bring up the suggest to change the default value of `isKeyPath` to `true`.

I might miss something, but please let me know what you think :-)

**Comment by JohnSundell** [comment]
Hi @Schaltfehler! Happy you like Unbox :)

See this discussion for the reasoning behind the `isKeyPath` parameter: https://github.com/JohnSundell/Unbox/issues/29.

However, I do agree with you, it's much more common to use `.` as a keypath than an actual key, so we should indeed change the default value to `true` :)

With Swift 3, I'm also considering making `key` and `keyPath` different argument labels in the method signature (a pattern which seems very encouraged in Swift 3), like this:

```
unbox(key: String) -> T
unbox(keyPath: String) -> T
```

But we can start by changing the default value of `isKeyPath` to true :)

**Comment by Schaltfehler** [comment]
That looks good. 
Clear, easy to understand of keeps the "control parameter" `isKeyPath` out.

**Comment by JohnSundell** [comment]
Fixed in https://github.com/JohnSundell/Unbox/commit/1a9edde98d065d01777bf55d3c8cfa6409eea118 🚀 

Will make a new release now!
