### ISSUE TITLE
Unable to unbox [NSURL]

### ISSUE THREAD

**Issue by ntnhon** [JohnSundell/Unbox#85]
Hi, I encounter problem unboxing an array of NSURL. It seems to be supported right in the box but somehow not working.

Here's the error message: 
![screen shot 2016-07-02 at 11 13 04 pm](https://cloud.githubusercontent.com/assets/4153453/16542485/bdbe566e-40aa-11e6-9c92-108f77a34fd3.png)

Am I missing something here?

Thank you.

**Comment by JohnSundell** [comment]
Hi @ntnhon, could you please post some sample code so that I can diagnose the problem?

**Comment by ntnhon** [comment]
Hi John,

Here is the exact code that I'm using. It's just simply not working...I have to workaround by using an intermediate [String]. Please have a look.

![screen shot 2016-07-04 at 10 30 18 am](https://cloud.githubusercontent.com/assets/4153453/16555003/a93ac19a-41d2-11e6-93c7-312c20ab063c.png)

**Comment by JohnSundell** [comment]
@ntnhon This was caused by a missing `unbox()` overload that @maxsz has now fixed 🎉
