### ISSUE TITLE
unboxing without struct

### ISSUE THREAD

**Issue by tcurdt** [JohnSundell/Unbox#86]
While most of the time the `struct` mapping approach is fine, I am wondering whether there is also a way to use `Unbox` without. Similar to what `SwiftyJSON` or `JASON` allows you to do. Basically allowing to use the `Unboxer` directly somehow.

**Comment by JohnSundell** [comment]
Hi @tcurdt, you can use the cusom Unboxing API for this. This enables you to get direct access to an `Unboxer`, to perform whatever operations you want together with it.

See [`Unboxer.performCustomUnboxingWithDictionary/Array`](https://github.com/JohnSundell/Unbox/blob/master/Sources/Unbox.swift#L406) for more information :)

**Comment by tcurdt** [comment]
Thanks! Would be great to add an example to the readme though.

**Comment by JohnSundell** [comment]
@tcurdt, there's already a section about the custom unboxing API with a code example in the README :) Check the section titled [**Custom unboxing**](https://github.com/JohnSundell/Unbox#custom-unboxing).

**Comment by tcurdt** [comment]
Doh! I guess I just didn't expect that to hid behind "custom unboxing" and/or `Unboxer.performCustomUnboxingWithDictionary`. Anyway! Thanks!
