### ISSUE TITLE
Unboxing string array to integer array?

### ISSUE THREAD

**Issue by bmt22033** [JohnSundell/Unbox#87]
Hi John.  I just discovered Unbox and it's awesome!  Thank you for creating and sharing it.  I've run into a small issue and I'm not sure what I'm doing wrong.  I have the following class:

```
final class Conversation: Unboxable {

	var participants: [Int]?
	var subject: String?
	var timestamp: Int?
	var conversationId: String?
	
	init(unboxer: Unboxer) {
		self.participants = unboxer.unbox("participants")
		self.subject = unboxer.unbox("subject")
		self.timestamp = unboxer.unbox("timestamp")
		self.conversationId = unboxer.unbox("conversationId")
	}
}
```

The JSON response from the server looks like this:

```
{
	"subject" : "subject line goes here",
	"participants" : [
		"201984",
		"237810",
		"149092",
		"202577"
	],
	"timestamp" : 1468322845885,
	"conversationId" : "9bf356d1-4823-11e6a51e-2d6dfda33d93"
}
```

As you can see, the participants array in the JSON is a string array and I'd like to transform it into an integer array when it's unboxed.  But when I run the code as it is above, the participants property in my class is nil after unboxing.  If I change its type to [String]?, then it unboxes ok so I'm wondering if arrays don't automagically get transformed from String -> Int like a single value does?  Thanks very much for any hints.

**Comment by bmt22033** [comment]
I'm not sure if this is the intended way to deal with this but I found that by chaining flatMap(), I was able to end up with an integer array of participants.

`self.participants = unboxer.unbox("participants")?.flatMap { Int($0) }`

**Comment by JohnSundell** [comment]
@bmt22033 Yeah, that's a good workaround for now. Will make sure to add this to the library, so it does it by default. Thanks for reporting!

**Comment by JohnSundell** [comment]
Hey @bmt22033, @clayellis has now implemented a fix for this, so you can just call `unbox()` to decode an array of strings into an array of ints, without having a workaround.
