### ISSUE TITLE
Extend Bool unboxing from String

### ISSUE THREAD

**Issue by jakunico** [JohnSundell/Unbox#89]
Hi!

We want our client to be as flexible as possible so we're looking forward to parse `String` to `Bool` as follows:

String Value | Unboxed Bool
---|---
"0" | false
"1" | true
"false" | false
"true" | true

We came up with this:

```
extension Bool: UnboxableRawType {
    
    public static func unboxFallbackValue() -> Bool {
        return false
    }
    
    public static func transformUnboxedInt(unboxedInt: Int) -> Bool? {
        return Bool(unboxedInt)
    }

    public static func transformUnboxedString(unboxedString: String) -> Bool? {
        
        if ["1", "true"].contains(unboxedString) {
            return true
        } else if ["0", "false"].contains(unboxedString) {
            return false
        } else {
            return nil
        }
        
    }
}
```

The problem is that `Bool` already conforms to that protocol in `Unbox.swift` so it gets a compiler warning. How can we achieve this behaviour in the cleanest way possible?

**Comment by JohnSundell** [comment]
Hey @jakunico, interesting! On one hand we could include this in Unbox itself, but it might lead to false positives for code that assumes stricter type-checking. One way of doing it without modifying the library would be to introduce an intermediary type, like this: 

```swift
struct BoolValue: UnboxableRawType {
    var bool: Bool

    static func unboxFallbackValue() -> BoolValue {
        return BoolValue()
    }

    static func transformUnboxedInt(unboxedInt: Int) -> BoolValue? {
        return BoolValue(Bool(unboxedInt))
    }

    static func transformUnboxedString(unboxedString: String) -> BoolValue? {
        if ["1", "true"].contains(unboxedString) {
            return BoolValue(true)
        } else if ["0", "false"].contains(unboxedString) {
            return BoolValue(false)
        } else {
            return nil
        }
    }

    init(_ bool: Bool = false) {
        self.bool = bool
    }
}
```

And then, when you perform Unboxing, use your new type:

```swift
struct MyModel: Unboxable {
    let bool: Bool

    init(unboxer: Unboxer) {
        self.bool = (unboxer.unbox("bool") as BoolValue).bool
    }
}
```

In terms of cleanliness, I don't know. It feels a bit strange to introduce a new type, but at the same time that new type doesn't leak outside of the unboxing function (the property itself can still remain a `Bool`).

Another option would be to patch Unbox to enable custom `true`/`false` values when unboxing a Bool. Like this:

```swift
self.bool = unboxer.unbox("bool", trueValues: ["1", "true"], falseValues: ["0", "false"])
```

Let me know how you want to proceed :)

**Comment by jakunico** [comment]
Thanks for the response John. A temporal solution we ended implementing is a proxy extension of `Unbox` that takes care of special cases (we had a few similar cases):
 
```swift
extension Unbox {

    //Unboxes a Bool value
    func mz_unbox(key: String) -> Bool {
        
        if let value = unbox(key) as String? {
            
            if ["0", "false"].contains(value.lowercaseString) {
                return false
            } else if ["1", "true"].contains(value.lowercaseString) {
                return true
            }
        }
        
        return unbox(key)
    }
}
```

Usage:

```
let value: Bool = unboxer.mz_unbox("key")
```

I'm still not so satisfied with this solution as we had to proxy a lot of functions, though we like how it turned at usage time.

From the solutions you proposed, I think the first is the one that appeals us the most as we could get rid of this proxy extension I mentioned, though the downside is that we lose that clean usage.

Another alternative solution that we thought about:

- Move extensions for raw types into separated `.swift` files
- By default `Unbox` comes bundled with all extensions.
- If you want to customize the behaviour for one of these, just don't include that file and write your own.

Let me know what you think about this last option.

**Comment by JohnSundell** [comment]
@jakunico Sorry for the late response. The extension system you proposed is very interesting and something we should consider for future versions of Unbox. Don't think we want to implement it as various files you choose to include or not since many people use Unbox & other libraries through a package manager (which will probably be even more popular when the Swift Package Manager gets released). As for the functionality you requested, it has been implemented by @frranck on `master`, so closing this issue for now :)
