### ISSUE TITLE
Problem with UnboxableEnum

### ISSUE THREAD

**Issue by qbraksa** [JohnSundell/Unbox#9]
I'm trying to use `UnboxableEnum`, but so far I couldn't make it work even though I'm using one of the code snippet in the docs (Unbox v1.1) : 

**Here's the snippet I'm using :**
```
enum SpaceShipType: UnboxableEnum {
    case Apollo
    case Sputnik
    
    static func unboxFallbackValue() {
        return .Apollo
    }
}
```

**Here's the 2 errors I'm getting :**

![viewcontroller_swift_ _edited](https://cloud.githubusercontent.com/assets/379453/11321628/7c7f5bbc-90bf-11e5-9a68-a484f4b41bce.jpg)

**Comment by JohnSundell** [comment]
Sorry about that, that example in the Readme was incorrect. Thanks for letting me know, I've now fixed it :)

What you need to do is to declare an explicit raw value type for your enum. That way the compiler will infer that your enum conforms to `RawRepresentable`, which will enable Unbox to create new instances of it from an unboxed raw value.

Please check the updated example in the Readme and let me know if you find any other issues :)

**Comment by qbraksa** [comment]
Thanks! Although the new example didn't work either, here's what worked for me though : 

```swift
enum SpaceShipType: Int, UnboxableEnum {
    case Apollo
    case Sputnik
    
    static func unboxFallbackValue() -> SpaceShipType {
        return .Apollo
    }
}
```

**Comment by JohnSundell** [comment]
Awesome, thanks a lot! Can't believe I missed the return type :)
