### ISSUE TITLE
How to test models without json?

### ISSUE THREAD

**Issue by Chiliec** [JohnSundell/Unbox#99]
I want to create structs with default constructor in tests, without creating testing json files. Can I do that? Or if I implement `Unboxable` protocol, I can use only `init(unboxer: Unboxer)` constructor?

**Comment by JohnSundell** [comment]
Sure, all you have to do to make the default constructor still generated by Swift is to implement `Unboxable` in an extension, like this:

```swift
struct User {
    var name: String
    var age: Int
}

extension User: Unboxable {
    init(unboxer: Unboxer) {
        self.name = unboxer.unbox("name")
        self.age = unboxer.unbox("age")
    }
}
```

**Comment by Chiliec** [comment]
Awesome! Thanks!
